[package]
name = "maxime15848/dioxus-ui"
version = "0.1.16"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
"/public" = "target/dx/dioxus-ui/debug/web/public"

[[command]]
name = "server"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/public"]
