// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

#[derive(Clone, Debug, PartialEq)]
pub enum CommandCategory {
    Components,
}

#[derive(Clone, Debug)]
pub struct CommandItemData {
    pub label: &'static str,
    pub href: &'static str,
    pub category: CommandCategory,
}

/// COMPONENTS_ITEMS
pub const COMPONENTS_ITEMS: &[CommandItemData] = &[
    CommandItemData {
        label: "Accordion",
        href: "/components/accordion",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Alert",
        href: "/components/alert",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Alert Dialog",
        href: "/components/alert-dialog",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Avatar",
        href: "/components/avatar",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Badge",
        href: "/components/badge",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Breadcrumb",
        href: "/components/breadcrumb",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Button",
        href: "/components/button",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Button Group",
        href: "/components/button-group",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Card",
        href: "/components/card",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Checkbox",
        href: "/components/checkbox",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Chips",
        href: "/components/chips",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Collapsible",
        href: "/components/collapsible",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Dialog",
        href: "/components/dialog",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Empty",
        href: "/components/empty",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Input",
        href: "/components/input",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Kbd",
        href: "/components/kbd",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Label",
        href: "/components/label",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Pagination",
        href: "/components/pagination",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Progress",
        href: "/components/progress",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Radio Group",
        href: "/components/radio-group",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Select Native",
        href: "/components/select-native",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Separator",
        href: "/components/separator",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Skeleton",
        href: "/components/skeleton",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Slider",
        href: "/components/slider",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Spinner",
        href: "/components/spinner",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Status",
        href: "/components/status",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Switch",
        href: "/components/switch",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Table",
        href: "/components/table",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Tabs",
        href: "/components/tabs",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Textarea",
        href: "/components/textarea",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Theme Toggle",
        href: "/components/theme-toggle",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Toggle",
        href: "/components/toggle",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Toggle Group",
        href: "/components/toggle-group",
        category: CommandCategory::Components,
    },
    CommandItemData {
        label: "Tooltip",
        href: "/components/tooltip",
        category: CommandCategory::Components,
    },
];
