// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

#[derive(Clone, Debug, PartialEq)]
pub enum CommandCategory {
    Components,
}

#[derive(Clone, Debug)]
pub struct CommandItemData {
    pub label: &'static str,
    pub href: &'static str,
    pub category: CommandCategory,
}

/// COMPONENTS_ITEMS
pub const COMPONENTS_ITEMS: &[CommandItemData] = &[
    CommandItemData { label: "Accordion", href: "/docs/accordion", category: CommandCategory::Components },
    CommandItemData { label: "Alert", href: "/docs/alert", category: CommandCategory::Components },
    CommandItemData { label: "Alert Dialog", href: "/docs/alert-dialog", category: CommandCategory::Components },
    CommandItemData { label: "Avatar", href: "/docs/avatar", category: CommandCategory::Components },
    CommandItemData { label: "Badge", href: "/docs/badge", category: CommandCategory::Components },
    CommandItemData { label: "Breadcrumb", href: "/docs/breadcrumb", category: CommandCategory::Components },
    CommandItemData { label: "Button", href: "/docs/button", category: CommandCategory::Components },
    CommandItemData { label: "Button Group", href: "/docs/button-group", category: CommandCategory::Components },
    CommandItemData { label: "Card", href: "/docs/card", category: CommandCategory::Components },
    CommandItemData { label: "Checkbox", href: "/docs/checkbox", category: CommandCategory::Components },
    CommandItemData { label: "Chips", href: "/docs/chips", category: CommandCategory::Components },
    CommandItemData { label: "Collapsible", href: "/docs/collapsible", category: CommandCategory::Components },
    CommandItemData { label: "Dialog", href: "/docs/dialog", category: CommandCategory::Components },
    CommandItemData { label: "Empty", href: "/docs/empty", category: CommandCategory::Components },
    CommandItemData { label: "Input", href: "/docs/input", category: CommandCategory::Components },
    CommandItemData { label: "Kbd", href: "/docs/kbd", category: CommandCategory::Components },
    CommandItemData { label: "Label", href: "/docs/label", category: CommandCategory::Components },
    CommandItemData { label: "Pagination", href: "/docs/pagination", category: CommandCategory::Components },
    CommandItemData { label: "Progress", href: "/docs/progress", category: CommandCategory::Components },
    CommandItemData { label: "Radio Group", href: "/docs/radio-group", category: CommandCategory::Components },
    CommandItemData { label: "Select Native", href: "/docs/select-native", category: CommandCategory::Components },
    CommandItemData { label: "Separator", href: "/docs/separator", category: CommandCategory::Components },
    CommandItemData { label: "Skeleton", href: "/docs/skeleton", category: CommandCategory::Components },
    CommandItemData { label: "Slider", href: "/docs/slider", category: CommandCategory::Components },
    CommandItemData { label: "Spinner", href: "/docs/spinner", category: CommandCategory::Components },
    CommandItemData { label: "Status", href: "/docs/status", category: CommandCategory::Components },
    CommandItemData { label: "Switch", href: "/docs/switch", category: CommandCategory::Components },
    CommandItemData { label: "Table", href: "/docs/table", category: CommandCategory::Components },
    CommandItemData { label: "Tabs", href: "/docs/tabs", category: CommandCategory::Components },
    CommandItemData { label: "Textarea", href: "/docs/textarea", category: CommandCategory::Components },
    CommandItemData { label: "Theme Toggle", href: "/docs/theme-toggle", category: CommandCategory::Components },
    CommandItemData { label: "Toggle", href: "/docs/toggle", category: CommandCategory::Components },
    CommandItemData { label: "Toggle Group", href: "/docs/toggle-group", category: CommandCategory::Components },
    CommandItemData { label: "Tooltip", href: "/docs/tooltip", category: CommandCategory::Components },
];
