// AUTO-GENERATED by build_registry - adjusted for the Dioxus docs router.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CommandCategory {
    Pages,
    Components,
    Hooks,
}

impl CommandCategory {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pages => "Pages",
            Self::Components => "Components",
            Self::Hooks => "Hooks",
        }
    }

    pub const fn slug(self) -> &'static str {
        match self {
            Self::Pages => "pages",
            Self::Components => "components",
            Self::Hooks => "hooks",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CommandItemData {
    pub label: &'static str,
    pub href: &'static str,
    pub category: CommandCategory,
    pub add_cmd: Option<&'static str>,
}

/// PAGES_ITEMS
pub const PAGES_ITEMS: &[CommandItemData] = &[
    CommandItemData { label: "Home", href: "/", category: CommandCategory::Pages, add_cmd: None },
    CommandItemData {
        label: "Components",
        href: "/components/button",
        category: CommandCategory::Pages,
        add_cmd: None,
    },
    CommandItemData { label: "CLI", href: "/components/button", category: CommandCategory::Pages, add_cmd: None },
    CommandItemData {
        label: "Installation",
        href: "/components/button",
        category: CommandCategory::Pages,
        add_cmd: None,
    },
];

/// COMPONENTS_ITEMS
pub const COMPONENTS_ITEMS: &[CommandItemData] = &[
    CommandItemData {
        label: "Accordion",
        href: "/components/accordion",
        category: CommandCategory::Components,
        add_cmd: Some("accordion"),
    },
    CommandItemData {
        label: "Alert",
        href: "/components/alert",
        category: CommandCategory::Components,
        add_cmd: Some("alert"),
    },
    CommandItemData {
        label: "Alert Dialog",
        href: "/components/alert-dialog",
        category: CommandCategory::Components,
        add_cmd: Some("alert_dialog"),
    },
    CommandItemData {
        label: "Animate",
        href: "/components/animate",
        category: CommandCategory::Components,
        add_cmd: Some("animate"),
    },
    CommandItemData {
        label: "Aspect Ratio",
        href: "/components/aspect-ratio",
        category: CommandCategory::Components,
        add_cmd: Some("aspect_ratio"),
    },
    CommandItemData {
        label: "Avatar",
        href: "/components/avatar",
        category: CommandCategory::Components,
        add_cmd: Some("avatar"),
    },
    CommandItemData {
        label: "Badge",
        href: "/components/badge",
        category: CommandCategory::Components,
        add_cmd: Some("badge"),
    },
    CommandItemData {
        label: "Bento Grid",
        href: "/components/bento-grid",
        category: CommandCategory::Components,
        add_cmd: Some("bento_grid"),
    },
    CommandItemData {
        label: "Bottom Nav",
        href: "/components/bottom-nav",
        category: CommandCategory::Components,
        add_cmd: Some("bottom_nav"),
    },
    CommandItemData {
        label: "Breadcrumb",
        href: "/components/breadcrumb",
        category: CommandCategory::Components,
        add_cmd: Some("breadcrumb"),
    },
    CommandItemData {
        label: "Button",
        href: "/components/button",
        category: CommandCategory::Components,
        add_cmd: Some("button"),
    },
    CommandItemData {
        label: "Button Group",
        href: "/components/button-group",
        category: CommandCategory::Components,
        add_cmd: Some("button_group"),
    },
    CommandItemData {
        label: "Callout",
        href: "/components/callout",
        category: CommandCategory::Components,
        add_cmd: Some("callout"),
    },
    CommandItemData {
        label: "Card",
        href: "/components/card",
        category: CommandCategory::Components,
        add_cmd: Some("card"),
    },
    CommandItemData {
        label: "Card Carousel",
        href: "/components/card-carousel",
        category: CommandCategory::Components,
        add_cmd: Some("card_carousel"),
    },
    CommandItemData {
        label: "Carousel",
        href: "/components/carousel",
        category: CommandCategory::Components,
        add_cmd: Some("carousel"),
    },
    CommandItemData {
        label: "Chat",
        href: "/components/chat",
        category: CommandCategory::Components,
        add_cmd: Some("chat"),
    },
    CommandItemData {
        label: "Checkbox",
        href: "/components/checkbox",
        category: CommandCategory::Components,
        add_cmd: Some("checkbox"),
    },
    CommandItemData {
        label: "Chips",
        href: "/components/chips",
        category: CommandCategory::Components,
        add_cmd: Some("chips"),
    },
    CommandItemData {
        label: "Collapsible",
        href: "/components/collapsible",
        category: CommandCategory::Components,
        add_cmd: Some("collapsible"),
    },
    CommandItemData {
        label: "Dialog",
        href: "/components/dialog",
        category: CommandCategory::Components,
        add_cmd: Some("dialog"),
    },
    CommandItemData {
        label: "Drawer",
        href: "/components/drawer",
        category: CommandCategory::Components,
        add_cmd: Some("drawer"),
    },
    CommandItemData {
        label: "Empty",
        href: "/components/empty",
        category: CommandCategory::Components,
        add_cmd: Some("empty"),
    },
    CommandItemData {
        label: "Expandable",
        href: "/components/expandable",
        category: CommandCategory::Components,
        add_cmd: Some("expandable"),
    },
    CommandItemData {
        label: "FAQ Transition",
        href: "/components/faq-transition",
        category: CommandCategory::Components,
        add_cmd: Some("faq_transition"),
    },
    CommandItemData {
        label: "Field",
        href: "/components/field",
        category: CommandCategory::Components,
        add_cmd: Some("field"),
    },
    CommandItemData {
        label: "Hover Card",
        href: "/components/hover-card",
        category: CommandCategory::Components,
        add_cmd: Some("hover_card"),
    },
    CommandItemData {
        label: "Image",
        href: "/components/image",
        category: CommandCategory::Components,
        add_cmd: Some("image"),
    },
    CommandItemData {
        label: "Input",
        href: "/components/input",
        category: CommandCategory::Components,
        add_cmd: Some("input"),
    },
    CommandItemData {
        label: "Input Group",
        href: "/components/input-group",
        category: CommandCategory::Components,
        add_cmd: Some("input_group"),
    },
    CommandItemData {
        label: "Input OTP",
        href: "/components/input-otp",
        category: CommandCategory::Components,
        add_cmd: Some("input_otp"),
    },
    CommandItemData {
        label: "Item",
        href: "/components/item",
        category: CommandCategory::Components,
        add_cmd: Some("item"),
    },
    CommandItemData {
        label: "Kbd",
        href: "/components/kbd",
        category: CommandCategory::Components,
        add_cmd: Some("kbd"),
    },
    CommandItemData {
        label: "Label",
        href: "/components/label",
        category: CommandCategory::Components,
        add_cmd: Some("label"),
    },
    CommandItemData {
        label: "Marquee",
        href: "/components/marquee",
        category: CommandCategory::Components,
        add_cmd: Some("marquee"),
    },
    CommandItemData {
        label: "Mask",
        href: "/components/mask",
        category: CommandCategory::Components,
        add_cmd: Some("mask"),
    },
    CommandItemData {
        label: "Pagination",
        href: "/components/pagination",
        category: CommandCategory::Components,
        add_cmd: Some("pagination"),
    },
    CommandItemData {
        label: "Popover",
        href: "/components/popover",
        category: CommandCategory::Components,
        add_cmd: Some("popover"),
    },
    CommandItemData {
        label: "Pressable",
        href: "/components/pressable",
        category: CommandCategory::Components,
        add_cmd: Some("pressable"),
    },
    CommandItemData {
        label: "Progress",
        href: "/components/progress",
        category: CommandCategory::Components,
        add_cmd: Some("progress"),
    },
    CommandItemData {
        label: "Radio Button",
        href: "/components/radio-button",
        category: CommandCategory::Components,
        add_cmd: Some("radio_button"),
    },
    CommandItemData {
        label: "Radio Button Group",
        href: "/components/radio-button-group",
        category: CommandCategory::Components,
        add_cmd: Some("radio_button_group"),
    },
    CommandItemData {
        label: "Radio Group",
        href: "/components/radio-group",
        category: CommandCategory::Components,
        add_cmd: Some("radio_group"),
    },
    CommandItemData {
        label: "Scroll Area",
        href: "/components/scroll-area",
        category: CommandCategory::Components,
        add_cmd: Some("scroll_area"),
    },
    CommandItemData {
        label: "Select Native",
        href: "/components/select-native",
        category: CommandCategory::Components,
        add_cmd: Some("select_native"),
    },
    CommandItemData {
        label: "Separator",
        href: "/components/separator",
        category: CommandCategory::Components,
        add_cmd: Some("separator"),
    },
    CommandItemData {
        label: "Sheet",
        href: "/components/sheet",
        category: CommandCategory::Components,
        add_cmd: Some("sheet"),
    },
    CommandItemData {
        label: "Shimmer",
        href: "/components/shimmer",
        category: CommandCategory::Components,
        add_cmd: Some("shimmer"),
    },
    CommandItemData {
        label: "Skeleton",
        href: "/components/skeleton",
        category: CommandCategory::Components,
        add_cmd: Some("skeleton"),
    },
    CommandItemData {
        label: "Slider",
        href: "/components/slider",
        category: CommandCategory::Components,
        add_cmd: Some("slider"),
    },
    CommandItemData {
        label: "Spinner",
        href: "/components/spinner",
        category: CommandCategory::Components,
        add_cmd: Some("spinner"),
    },
    CommandItemData {
        label: "Status",
        href: "/components/status",
        category: CommandCategory::Components,
        add_cmd: Some("status"),
    },
    CommandItemData {
        label: "Switch",
        href: "/components/switch",
        category: CommandCategory::Components,
        add_cmd: Some("switch"),
    },
    CommandItemData {
        label: "Table",
        href: "/components/table",
        category: CommandCategory::Components,
        add_cmd: Some("table"),
    },
    CommandItemData {
        label: "Tabs",
        href: "/components/tabs",
        category: CommandCategory::Components,
        add_cmd: Some("tabs"),
    },
    CommandItemData {
        label: "Textarea",
        href: "/components/textarea",
        category: CommandCategory::Components,
        add_cmd: Some("textarea"),
    },
    CommandItemData {
        label: "Theme Toggle",
        href: "/components/theme-toggle",
        category: CommandCategory::Components,
        add_cmd: Some("theme_toggle"),
    },
    CommandItemData {
        label: "Toggle",
        href: "/components/toggle",
        category: CommandCategory::Components,
        add_cmd: Some("toggle"),
    },
    CommandItemData {
        label: "Toggle Group",
        href: "/components/toggle-group",
        category: CommandCategory::Components,
        add_cmd: Some("toggle_group"),
    },
    CommandItemData {
        label: "Tooltip",
        href: "/components/tooltip",
        category: CommandCategory::Components,
        add_cmd: Some("tooltip"),
    },
];

/// HOOKS_ITEMS
pub const HOOKS_ITEMS: &[CommandItemData] = &[
    CommandItemData {
        label: "Use Can Scroll",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Can Scroll Vertical",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Click Outside",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Copy Clipboard",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Data Scrolled",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Horizontal Scroll",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Is Mobile",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Media Query",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Press Hold",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Random",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Scroll Lock",
        href: "/components/button",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
    CommandItemData {
        label: "Use Theme Mode",
        href: "/components/theme-toggle",
        category: CommandCategory::Hooks,
        add_cmd: None,
    },
];
