// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

pub mod all_blocks;
pub mod command_bar;
pub mod sidenav;
pub mod sidenav_hooks;
pub mod source_map;
