// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use crate::__registry__::sidenav::SidenavItem;

pub static SIDENAV_HOOKS_ITEMS: &[SidenavItem] = &[
    SidenavItem { label: "Use Copy Clipboard", slug: "use-copy-clipboard" },
    SidenavItem { label: "Use Lock Body Scroll", slug: "use-lock-body-scroll" },
    SidenavItem { label: "Use Random", slug: "use-random" },
];
