// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_accordion::DemoAccordion;
use registry::demos::demo_accordion_bordered::DemoAccordionBordered;
use registry::demos::demo_alert::DemoAlert;
use registry::demos::demo_alert_dialog::DemoAlertDialog;
use registry::demos::demo_alert_dialog_small_media::DemoAlertDialogSmallMedia;
use registry::demos::demo_animate::DemoAnimate;
use registry::demos::demo_animate_group::DemoAnimateGroup;
use registry::demos::demo_aspect_ratio::DemoAspectRatio;
use registry::demos::demo_attachment::DemoAttachment;
use registry::demos::demo_attachment_group::DemoAttachmentGroup;
use registry::demos::demo_attachment_image::DemoAttachmentImage;
use registry::demos::demo_attachment_sizes::DemoAttachmentSizes;
use registry::demos::demo_attachment_states::DemoAttachmentStates;
use registry::demos::demo_attachment_trigger::DemoAttachmentTrigger;
use registry::demos::demo_auto_form::DemoAutoForm;
use registry::demos::demo_avatar::DemoAvatar;
use registry::demos::demo_avatar_group_count_icon::DemoAvatarGroupCountIcon;
use registry::demos::demo_badge::DemoBadge;
use registry::demos::demo_badge_colors::DemoBadgeColors;
use registry::demos::demo_badge_custom::DemoBadgeCustom;
use registry::demos::demo_badge_variants::DemoBadgeVariants;
use registry::demos::demo_bento_grid::DemoBentoGrid;
use registry::demos::demo_bento_grid6::DemoBentoGrid6;
use registry::demos::demo_bottom_nav::DemoBottomNav;
use registry::demos::demo_breadcrumb::DemoBreadcrumb;
use registry::demos::demo_breadcrumb_rtl::DemoBreadcrumbRtl;
use registry::demos::demo_bubble::DemoBubble;
use registry::demos::demo_bubble_alignment::DemoBubbleAlignment;
use registry::demos::demo_bubble_collapsible::DemoBubbleCollapsible;
use registry::demos::demo_bubble_group::DemoBubbleGroup;
use registry::demos::demo_bubble_link_button::DemoBubbleLinkButton;
use registry::demos::demo_bubble_popover::DemoBubblePopover;
use registry::demos::demo_bubble_reactions::DemoBubbleReactions;
use registry::demos::demo_bubble_tooltip::DemoBubbleTooltip;
use registry::demos::demo_bubble_variants::DemoBubbleVariants;
use registry::demos::demo_button::DemoButton;
use registry::demos::demo_button_action::DemoButtonAction;
use registry::demos::demo_button_disabled::DemoButtonDisabled;
use registry::demos::demo_button_group::DemoButtonGroup;
use registry::demos::demo_button_group_icon::DemoButtonGroupIcon;
use registry::demos::demo_button_group_input::DemoButtonGroupInput;
use registry::demos::demo_button_group_rtl::DemoButtonGroupRtl;
use registry::demos::demo_button_group_separator::DemoButtonGroupSeparator;
use registry::demos::demo_button_group_sizes::DemoButtonGroupSizes;
use registry::demos::demo_button_href::DemoButtonHref;
use registry::demos::demo_button_override::DemoButtonOverride;
use registry::demos::demo_button_reactive::DemoButtonReactive;
use registry::demos::demo_button_rtl::DemoButtonRtl;
use registry::demos::demo_button_sizes::DemoButtonSizes;
use registry::demos::demo_button_stateful::DemoButtonStateful;
use registry::demos::demo_button_variants::DemoButtonVariants;
use registry::demos::demo_callout::DemoCallout;
use registry::demos::demo_callout_info::DemoCalloutInfo;
use registry::demos::demo_callout_warning::DemoCalloutWarning;
use registry::demos::demo_card::DemoCard;
use registry::demos::demo_card_action::DemoCardAction;
use registry::demos::demo_card_carousel::DemoCardCarousel;
use registry::demos::demo_card_group::DemoCardGroup;
use registry::demos::demo_card_reverse::DemoCardReverse;
use registry::demos::demo_card_sm::DemoCardSm;
use registry::demos::demo_carousel::DemoCarousel;
use registry::demos::demo_chat::DemoChat;
use registry::demos::demo_checkbox::DemoCheckbox;
use registry::demos::demo_chips::DemoChips;
use registry::demos::demo_collapsible::DemoCollapsible;
use registry::demos::demo_collapsible_settings::DemoCollapsibleSettings;
use registry::demos::demo_combobox::DemoCombobox;
use registry::demos::demo_command::DemoCommand;
use registry::demos::demo_command_dialog::DemoCommandDialog;
use registry::demos::demo_context_menu::DemoContextMenu;
use registry::demos::demo_context_menu_action::DemoContextMenuAction;
use registry::demos::demo_context_menu_rtl::DemoContextMenuRtl;
use registry::demos::demo_data_grid::DemoDataGrid;
use registry::demos::demo_data_table::DemoDataTable;
use registry::demos::demo_data_table_filters::DemoDataTableFilters;
use registry::demos::demo_date_picker::DemoDatePicker;
use registry::demos::demo_date_picker_booked::DemoDatePickerBooked;
use registry::demos::demo_date_picker_dropdown::DemoDatePickerDropdown;
use registry::demos::demo_date_picker_dual::DemoDatePickerDual;
use registry::demos::demo_date_picker_dual_full::DemoDatePickerDualFull;
use registry::demos::demo_date_picker_presets::DemoDatePickerPresets;
use registry::demos::demo_date_picker_time::DemoDatePickerTime;
use registry::demos::demo_date_picker_week_numbers::DemoDatePickerWeekNumbers;
use registry::demos::demo_dialog::DemoDialog;
use registry::demos::demo_dialog_scrollable::DemoDialogScrollable;
use registry::demos::demo_direction_provider::DemoDirectionProvider;
use registry::demos::demo_direction_provider_default::DemoDirectionProviderDefault;
use registry::demos::demo_direction_provider_rtl::DemoDirectionProviderRtl;
use registry::demos::demo_drag_and_drop::DemoDragAndDrop;
use registry::demos::demo_drawer::DemoDrawer;
use registry::demos::demo_dropdown_menu::DemoDropdownMenu;
use registry::demos::demo_dropdown_menu_destructive::DemoDropdownMenuDestructive;
use registry::demos::demo_dropdown_menu_end::DemoDropdownMenuEnd;
use registry::demos::demo_dropdown_menu_end_outer::DemoDropdownMenuEndOuter;
use registry::demos::demo_dropdown_menu_radio::DemoDropdownMenuRadio;
use registry::demos::demo_dropdown_menu_rtl::DemoDropdownMenuRtl;
use registry::demos::demo_dropdown_menu_select::DemoDropdownMenuSelect;
use registry::demos::demo_dropdown_menu_start::DemoDropdownMenuStart;
use registry::demos::demo_dropdown_menu_start_outer::DemoDropdownMenuStartOuter;
use registry::demos::demo_dropdown_menu_user::DemoDropdownMenuUser;
use registry::demos::demo_dropdown_menu_user_icon::DemoDropdownMenuUserIcon;
use registry::demos::demo_dropzone::DemoDropzone;
use registry::demos::demo_dropzone_grid::DemoDropzoneGrid;
use registry::demos::demo_dropzone_toggle::DemoDropzoneToggle;
use registry::demos::demo_empty::DemoEmpty;
use registry::demos::demo_empty_muted::DemoEmptyMuted;
use registry::demos::demo_expandable::DemoExpandable;
use registry::demos::demo_faq_transition::DemoFaqTransition;
use registry::demos::demo_field::DemoField;
use registry::demos::demo_field_rtl::DemoFieldRtl;
use registry::demos::demo_form::DemoForm;
use registry::demos::demo_form_error::DemoFormError;
use registry::demos::demo_form_fieldset::DemoFormFieldset;
use registry::demos::demo_form_group::DemoFormGroup;
use registry::demos::demo_form_select::DemoFormSelect;
use registry::demos::demo_form_validation::DemoFormValidation;
use registry::demos::demo_hover_card::DemoHoverCard;
use registry::demos::demo_hover_card_rtl::DemoHoverCardRtl;
use registry::demos::demo_image::DemoImage;
use registry::demos::demo_input::DemoInput;
use registry::demos::demo_input_copy::DemoInputCopy;
use registry::demos::demo_input_group::DemoInputGroup;
use registry::demos::demo_input_group_block::DemoInputGroupBlock;
use registry::demos::demo_input_group_rtl::DemoInputGroupRtl;
use registry::demos::demo_input_group_text::DemoInputGroupText;
use registry::demos::demo_input_otp::DemoInputOtp;
use registry::demos::demo_input_otp_separator::DemoInputOtpSeparator;
use registry::demos::demo_input_phone::DemoInputPhone;
use registry::demos::demo_input_phone_disabled::DemoInputPhoneDisabled;
use registry::demos::demo_input_prompt::DemoInputPrompt;
use registry::demos::demo_input_prompt_with_tools::DemoInputPromptWithTools;
use registry::demos::demo_item::DemoItem;
use registry::demos::demo_kbd::DemoKbd;
use registry::demos::demo_label::DemoLabel;
use registry::demos::demo_marker::DemoMarker;
use registry::demos::demo_marker_border::DemoMarkerBorder;
use registry::demos::demo_marker_icon::DemoMarkerIcon;
use registry::demos::demo_marker_link_button::DemoMarkerLinkButton;
use registry::demos::demo_marker_separator::DemoMarkerSeparator;
use registry::demos::demo_marker_shimmer::DemoMarkerShimmer;
use registry::demos::demo_marker_status::DemoMarkerStatus;
use registry::demos::demo_marker_variants::DemoMarkerVariants;
use registry::demos::demo_marquee::DemoMarquee;
use registry::demos::demo_mask::DemoMask;
use registry::demos::demo_menubar::DemoMenubar;
use registry::demos::demo_menubar_rtl::DemoMenubarRtl;
use registry::demos::demo_message::DemoMessage;
use registry::demos::demo_message_actions::DemoMessageActions;
use registry::demos::demo_message_attachment::DemoMessageAttachment;
use registry::demos::demo_message_avatar::DemoMessageAvatar;
use registry::demos::demo_message_group::DemoMessageGroup;
use registry::demos::demo_message_header_footer::DemoMessageHeaderFooter;
use registry::demos::demo_multi_select::DemoMultiSelect;
use registry::demos::demo_multi_select_align::DemoMultiSelectAlign;
use registry::demos::demo_multi_select_scrollable::DemoMultiSelectScrollable;
use registry::demos::demo_navigation_menu::DemoNavigationMenu;
use registry::demos::demo_navigation_menu_complex::DemoNavigationMenuComplex;
use registry::demos::demo_navigation_menu_rtl::DemoNavigationMenuRtl;
use registry::demos::demo_pagination::DemoPagination;
use registry::demos::demo_popover::DemoPopover;
use registry::demos::demo_pressable::DemoPressable;
use registry::demos::demo_progress::DemoProgress;
use registry::demos::demo_radio_button::DemoRadioButton;
use registry::demos::demo_radio_button_custom::DemoRadioButtonCustom;
use registry::demos::demo_radio_button_group::DemoRadioButtonGroup;
use registry::demos::demo_radio_button_group_rtl::DemoRadioButtonGroupRtl;
use registry::demos::demo_radio_group::DemoRadioGroup;
use registry::demos::demo_scroll_area::DemoScrollArea;
use registry::demos::demo_scroll_area_horizontal::DemoScrollAreaHorizontal;
use registry::demos::demo_scroll_area_rtl::DemoScrollAreaRtl;
use registry::demos::demo_select::DemoSelect;
use registry::demos::demo_select_native_group::DemoSelectNativeGroup;
use registry::demos::demo_select_rtl::DemoSelectRtl;
use registry::demos::demo_select_scrollable::DemoSelectScrollable;
use registry::demos::demo_separator::DemoSeparator;
use registry::demos::demo_sheet::DemoSheet;
use registry::demos::demo_shimmer::DemoShimmer;
use registry::demos::demo_skeleton::DemoSkeleton;
use registry::demos::demo_skeleton_avatar::DemoSkeletonAvatar;
use registry::demos::demo_skeleton_form::DemoSkeletonForm;
use registry::demos::demo_skeleton_image::DemoSkeletonImage;
use registry::demos::demo_skeleton_table::DemoSkeletonTable;
use registry::demos::demo_skeleton_text::DemoSkeletonText;
use registry::demos::demo_slider::DemoSlider;
use registry::demos::demo_sonner::DemoSonner;
use registry::demos::demo_sonner_positions::DemoSonnerPositions;
use registry::demos::demo_sonner_variants::DemoSonnerVariants;
use registry::demos::demo_spinner::DemoSpinner;
use registry::demos::demo_spinner_button::DemoSpinnerButton;
use registry::demos::demo_status::DemoStatus;
use registry::demos::demo_status_variants::DemoStatusVariants;
use registry::demos::demo_stepper::DemoStepper;
use registry::demos::demo_stepper_controlled::DemoStepperControlled;
use registry::demos::demo_stepper_vertical::DemoStepperVertical;
use registry::demos::demo_switch::DemoSwitch;
use registry::demos::demo_table::DemoTable;
use registry::demos::demo_tabs::DemoTabs;
use registry::demos::demo_textarea::DemoTextarea;
use registry::demos::demo_theme_toggle::DemoThemeToggle;
use registry::demos::demo_toast::DemoToast;
use registry::demos::demo_toast_variants::DemoToastVariants;
use registry::demos::demo_toggle::DemoToggle;
use registry::demos::demo_toggle_group::DemoToggleGroup;
use registry::demos::demo_toolbar::DemoToolbar;
use registry::demos::demo_tooltip::DemoTooltip;

use crate::domain::markdown_ui::components::static_demo_wrapper::StaticDemoWrapper;
use crate::domain::markdown_ui::components::static_install_wrapper::StaticInstallWrapper;
use crate::domain::markdown_ui::components::static_md_docs_wrapper::StaticMdDocsWrapper;
use crate::markdown::converter::{convert_md, MdComponents};
use crate::markdown::parse_md;
use crate::registry::md_docs::docs_installation_cli_tree_view::DocsInstallationCliTreeView;
use crate::registry::types::RegistryEntry;

#[component]
pub fn MyMd(raw: &'static str) -> Element {
    let (_, body) = parse_md(raw);
    let components = build_md_components();
    convert_md(body, &components)
}

fn build_md_components() -> MdComponents {
    let mut combined_components = MdComponents::new();
    combined_components.add("DocsInstallationCliTreeView", |_| rsx! {
        StaticMdDocsWrapper {
            DocsInstallationCliTreeView {}
        }
    });
    combined_components.add("DemoAccordion", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAccordion",
            DemoAccordion {}
        }
    });
    combined_components.add("DemoAccordionBordered", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAccordionBordered",
            DemoAccordionBordered {}
        }
    });
    combined_components.add("DemoAlert", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAlert",
            DemoAlert {}
        }
    });
    combined_components.add("DemoAlertDialog", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAlertDialog",
            DemoAlertDialog {}
        }
    });
    combined_components.add("DemoAlertDialogSmallMedia", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAlertDialogSmallMedia",
            DemoAlertDialogSmallMedia {}
        }
    });
    combined_components.add("DemoAnimate", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAnimate",
            DemoAnimate {}
        }
    });
    combined_components.add("DemoAnimateGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAnimateGroup",
            DemoAnimateGroup {}
        }
    });
    combined_components.add("DemoAspectRatio", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAspectRatio",
            DemoAspectRatio {}
        }
    });
    combined_components.add("DemoAttachment", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAttachment",
            DemoAttachment {}
        }
    });
    combined_components.add("DemoAttachmentGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAttachmentGroup",
            DemoAttachmentGroup {}
        }
    });
    combined_components.add("DemoAttachmentImage", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAttachmentImage",
            DemoAttachmentImage {}
        }
    });
    combined_components.add("DemoAttachmentSizes", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAttachmentSizes",
            DemoAttachmentSizes {}
        }
    });
    combined_components.add("DemoAttachmentStates", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAttachmentStates",
            DemoAttachmentStates {}
        }
    });
    combined_components.add("DemoAttachmentTrigger", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAttachmentTrigger",
            DemoAttachmentTrigger {}
        }
    });
    combined_components.add("DemoAutoForm", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAutoForm",
            DemoAutoForm {}
        }
    });
    combined_components.add("DemoAvatar", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAvatar",
            DemoAvatar {}
        }
    });
    combined_components.add("DemoAvatarGroupCountIcon", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoAvatarGroupCountIcon",
            DemoAvatarGroupCountIcon {}
        }
    });
    combined_components.add("DemoBadge", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBadge",
            DemoBadge {}
        }
    });
    combined_components.add("DemoBadgeColors", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBadgeColors",
            DemoBadgeColors {}
        }
    });
    combined_components.add("DemoBadgeCustom", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBadgeCustom",
            DemoBadgeCustom {}
        }
    });
    combined_components.add("DemoBadgeVariants", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBadgeVariants",
            DemoBadgeVariants {}
        }
    });
    combined_components.add("DemoBentoGrid", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBentoGrid",
            DemoBentoGrid {}
        }
    });
    combined_components.add("DemoBentoGrid6", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBentoGrid6",
            DemoBentoGrid6 {}
        }
    });
    combined_components.add("DemoBottomNav", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBottomNav",
            DemoBottomNav {}
        }
    });
    combined_components.add("DemoBreadcrumb", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBreadcrumb",
            DemoBreadcrumb {}
        }
    });
    combined_components.add("DemoBreadcrumbRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBreadcrumbRtl",
            DemoBreadcrumbRtl {}
        }
    });
    combined_components.add("DemoBubble", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubble",
            DemoBubble {}
        }
    });
    combined_components.add("DemoBubbleAlignment", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubbleAlignment",
            DemoBubbleAlignment {}
        }
    });
    combined_components.add("DemoBubbleCollapsible", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubbleCollapsible",
            DemoBubbleCollapsible {}
        }
    });
    combined_components.add("DemoBubbleGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubbleGroup",
            DemoBubbleGroup {}
        }
    });
    combined_components.add("DemoBubbleLinkButton", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubbleLinkButton",
            DemoBubbleLinkButton {}
        }
    });
    combined_components.add("DemoBubblePopover", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubblePopover",
            DemoBubblePopover {}
        }
    });
    combined_components.add("DemoBubbleReactions", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubbleReactions",
            DemoBubbleReactions {}
        }
    });
    combined_components.add("DemoBubbleTooltip", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubbleTooltip",
            DemoBubbleTooltip {}
        }
    });
    combined_components.add("DemoBubbleVariants", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoBubbleVariants",
            DemoBubbleVariants {}
        }
    });
    combined_components.add("DemoButton", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButton",
            DemoButton {}
        }
    });
    combined_components.add("DemoButtonAction", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonAction",
            DemoButtonAction {}
        }
    });
    combined_components.add("DemoButtonDisabled", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonDisabled",
            DemoButtonDisabled {}
        }
    });
    combined_components.add("DemoButtonGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonGroup",
            DemoButtonGroup {}
        }
    });
    combined_components.add("DemoButtonGroupIcon", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonGroupIcon",
            DemoButtonGroupIcon {}
        }
    });
    combined_components.add("DemoButtonGroupInput", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonGroupInput",
            DemoButtonGroupInput {}
        }
    });
    combined_components.add("DemoButtonGroupRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonGroupRtl",
            DemoButtonGroupRtl {}
        }
    });
    combined_components.add("DemoButtonGroupSeparator", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonGroupSeparator",
            DemoButtonGroupSeparator {}
        }
    });
    combined_components.add("DemoButtonGroupSizes", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonGroupSizes",
            DemoButtonGroupSizes {}
        }
    });
    combined_components.add("DemoButtonHref", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonHref",
            DemoButtonHref {}
        }
    });
    combined_components.add("DemoButtonOverride", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonOverride",
            DemoButtonOverride {}
        }
    });
    combined_components.add("DemoButtonReactive", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonReactive",
            DemoButtonReactive {}
        }
    });
    combined_components.add("DemoButtonRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonRtl",
            DemoButtonRtl {}
        }
    });
    combined_components.add("DemoButtonSizes", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonSizes",
            DemoButtonSizes {}
        }
    });
    combined_components.add("DemoButtonStateful", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonStateful",
            DemoButtonStateful {}
        }
    });
    combined_components.add("DemoButtonVariants", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoButtonVariants",
            DemoButtonVariants {}
        }
    });
    combined_components.add("DemoCallout", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCallout",
            DemoCallout {}
        }
    });
    combined_components.add("DemoCalloutInfo", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCalloutInfo",
            DemoCalloutInfo {}
        }
    });
    combined_components.add("DemoCalloutWarning", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCalloutWarning",
            DemoCalloutWarning {}
        }
    });
    combined_components.add("DemoCard", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCard",
            DemoCard {}
        }
    });
    combined_components.add("DemoCardAction", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCardAction",
            DemoCardAction {}
        }
    });
    combined_components.add("DemoCardCarousel", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCardCarousel",
            DemoCardCarousel {}
        }
    });
    combined_components.add("DemoCardGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCardGroup",
            DemoCardGroup {}
        }
    });
    combined_components.add("DemoCardReverse", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCardReverse",
            DemoCardReverse {}
        }
    });
    combined_components.add("DemoCardSm", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCardSm",
            DemoCardSm {}
        }
    });
    combined_components.add("DemoCarousel", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCarousel",
            DemoCarousel {}
        }
    });
    combined_components.add("DemoChat", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoChat",
            DemoChat {}
        }
    });
    combined_components.add("DemoCheckbox", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCheckbox",
            DemoCheckbox {}
        }
    });
    combined_components.add("DemoChips", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoChips",
            DemoChips {}
        }
    });
    combined_components.add("DemoCollapsible", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCollapsible",
            DemoCollapsible {}
        }
    });
    combined_components.add("DemoCollapsibleSettings", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCollapsibleSettings",
            DemoCollapsibleSettings {}
        }
    });
    combined_components.add("DemoCombobox", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCombobox",
            DemoCombobox {}
        }
    });
    combined_components.add("DemoCommand", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCommand",
            DemoCommand {}
        }
    });
    combined_components.add("DemoCommandDialog", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoCommandDialog",
            DemoCommandDialog {}
        }
    });
    combined_components.add("DemoContextMenu", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoContextMenu",
            DemoContextMenu {}
        }
    });
    combined_components.add("DemoContextMenuAction", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoContextMenuAction",
            DemoContextMenuAction {}
        }
    });
    combined_components.add("DemoContextMenuRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoContextMenuRtl",
            DemoContextMenuRtl {}
        }
    });
    combined_components.add("DemoDataGrid", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDataGrid",
            DemoDataGrid {}
        }
    });
    combined_components.add("DemoDataTable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDataTable",
            DemoDataTable {}
        }
    });
    combined_components.add("DemoDataTableFilters", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDataTableFilters",
            DemoDataTableFilters {}
        }
    });
    combined_components.add("DemoDatePicker", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePicker",
            DemoDatePicker {}
        }
    });
    combined_components.add("DemoDatePickerBooked", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePickerBooked",
            DemoDatePickerBooked {}
        }
    });
    combined_components.add("DemoDatePickerDropdown", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePickerDropdown",
            DemoDatePickerDropdown {}
        }
    });
    combined_components.add("DemoDatePickerDual", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePickerDual",
            DemoDatePickerDual {}
        }
    });
    combined_components.add("DemoDatePickerDualFull", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePickerDualFull",
            DemoDatePickerDualFull {}
        }
    });
    combined_components.add("DemoDatePickerPresets", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePickerPresets",
            DemoDatePickerPresets {}
        }
    });
    combined_components.add("DemoDatePickerTime", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePickerTime",
            DemoDatePickerTime {}
        }
    });
    combined_components.add("DemoDatePickerWeekNumbers", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDatePickerWeekNumbers",
            DemoDatePickerWeekNumbers {}
        }
    });
    combined_components.add("DemoDialog", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDialog",
            DemoDialog {}
        }
    });
    combined_components.add("DemoDialogScrollable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDialogScrollable",
            DemoDialogScrollable {}
        }
    });
    combined_components.add("DemoDirectionProvider", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDirectionProvider",
            DemoDirectionProvider {}
        }
    });
    combined_components.add("DemoDirectionProviderDefault", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDirectionProviderDefault",
            DemoDirectionProviderDefault {}
        }
    });
    combined_components.add("DemoDirectionProviderRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDirectionProviderRtl",
            DemoDirectionProviderRtl {}
        }
    });
    combined_components.add("DemoDragAndDrop", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDragAndDrop",
            DemoDragAndDrop {}
        }
    });
    combined_components.add("DemoDrawer", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDrawer",
            DemoDrawer {}
        }
    });
    combined_components.add("DemoDropdownMenu", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenu",
            DemoDropdownMenu {}
        }
    });
    combined_components.add("DemoDropdownMenuDestructive", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuDestructive",
            DemoDropdownMenuDestructive {}
        }
    });
    combined_components.add("DemoDropdownMenuEnd", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuEnd",
            DemoDropdownMenuEnd {}
        }
    });
    combined_components.add("DemoDropdownMenuEndOuter", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuEndOuter",
            DemoDropdownMenuEndOuter {}
        }
    });
    combined_components.add("DemoDropdownMenuRadio", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuRadio",
            DemoDropdownMenuRadio {}
        }
    });
    combined_components.add("DemoDropdownMenuRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuRtl",
            DemoDropdownMenuRtl {}
        }
    });
    combined_components.add("DemoDropdownMenuSelect", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuSelect",
            DemoDropdownMenuSelect {}
        }
    });
    combined_components.add("DemoDropdownMenuStart", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuStart",
            DemoDropdownMenuStart {}
        }
    });
    combined_components.add("DemoDropdownMenuStartOuter", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuStartOuter",
            DemoDropdownMenuStartOuter {}
        }
    });
    combined_components.add("DemoDropdownMenuUser", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuUser",
            DemoDropdownMenuUser {}
        }
    });
    combined_components.add("DemoDropdownMenuUserIcon", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropdownMenuUserIcon",
            DemoDropdownMenuUserIcon {}
        }
    });
    combined_components.add("DemoDropzone", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropzone",
            DemoDropzone {}
        }
    });
    combined_components.add("DemoDropzoneGrid", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropzoneGrid",
            DemoDropzoneGrid {}
        }
    });
    combined_components.add("DemoDropzoneToggle", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoDropzoneToggle",
            DemoDropzoneToggle {}
        }
    });
    combined_components.add("DemoEmpty", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoEmpty",
            DemoEmpty {}
        }
    });
    combined_components.add("DemoEmptyMuted", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoEmptyMuted",
            DemoEmptyMuted {}
        }
    });
    combined_components.add("DemoExpandable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoExpandable",
            DemoExpandable {}
        }
    });
    combined_components.add("DemoFaqTransition", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoFaqTransition",
            DemoFaqTransition {}
        }
    });
    combined_components.add("DemoField", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoField",
            DemoField {}
        }
    });
    combined_components.add("DemoFieldRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoFieldRtl",
            DemoFieldRtl {}
        }
    });
    combined_components.add("DemoForm", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoForm",
            DemoForm {}
        }
    });
    combined_components.add("DemoFormError", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoFormError",
            DemoFormError {}
        }
    });
    combined_components.add("DemoFormFieldset", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoFormFieldset",
            DemoFormFieldset {}
        }
    });
    combined_components.add("DemoFormGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoFormGroup",
            DemoFormGroup {}
        }
    });
    combined_components.add("DemoFormSelect", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoFormSelect",
            DemoFormSelect {}
        }
    });
    combined_components.add("DemoFormValidation", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoFormValidation",
            DemoFormValidation {}
        }
    });
    combined_components.add("DemoHoverCard", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoHoverCard",
            DemoHoverCard {}
        }
    });
    combined_components.add("DemoHoverCardRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoHoverCardRtl",
            DemoHoverCardRtl {}
        }
    });
    combined_components.add("DemoImage", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoImage",
            DemoImage {}
        }
    });
    combined_components.add("DemoInput", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInput",
            DemoInput {}
        }
    });
    combined_components.add("DemoInputCopy", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputCopy",
            DemoInputCopy {}
        }
    });
    combined_components.add("DemoInputGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputGroup",
            DemoInputGroup {}
        }
    });
    combined_components.add("DemoInputGroupBlock", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputGroupBlock",
            DemoInputGroupBlock {}
        }
    });
    combined_components.add("DemoInputGroupRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputGroupRtl",
            DemoInputGroupRtl {}
        }
    });
    combined_components.add("DemoInputGroupText", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputGroupText",
            DemoInputGroupText {}
        }
    });
    combined_components.add("DemoInputOtp", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputOtp",
            DemoInputOtp {}
        }
    });
    combined_components.add("DemoInputOtpSeparator", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputOtpSeparator",
            DemoInputOtpSeparator {}
        }
    });
    combined_components.add("DemoInputPhone", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputPhone",
            DemoInputPhone {}
        }
    });
    combined_components.add("DemoInputPhoneDisabled", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputPhoneDisabled",
            DemoInputPhoneDisabled {}
        }
    });
    combined_components.add("DemoInputPrompt", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputPrompt",
            DemoInputPrompt {}
        }
    });
    combined_components.add("DemoInputPromptWithTools", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoInputPromptWithTools",
            DemoInputPromptWithTools {}
        }
    });
    combined_components.add("DemoItem", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoItem",
            DemoItem {}
        }
    });
    combined_components.add("DemoKbd", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoKbd",
            DemoKbd {}
        }
    });
    combined_components.add("DemoLabel", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoLabel",
            DemoLabel {}
        }
    });
    combined_components.add("DemoMarker", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarker",
            DemoMarker {}
        }
    });
    combined_components.add("DemoMarkerBorder", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarkerBorder",
            DemoMarkerBorder {}
        }
    });
    combined_components.add("DemoMarkerIcon", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarkerIcon",
            DemoMarkerIcon {}
        }
    });
    combined_components.add("DemoMarkerLinkButton", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarkerLinkButton",
            DemoMarkerLinkButton {}
        }
    });
    combined_components.add("DemoMarkerSeparator", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarkerSeparator",
            DemoMarkerSeparator {}
        }
    });
    combined_components.add("DemoMarkerShimmer", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarkerShimmer",
            DemoMarkerShimmer {}
        }
    });
    combined_components.add("DemoMarkerStatus", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarkerStatus",
            DemoMarkerStatus {}
        }
    });
    combined_components.add("DemoMarkerVariants", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarkerVariants",
            DemoMarkerVariants {}
        }
    });
    combined_components.add("DemoMarquee", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMarquee",
            DemoMarquee {}
        }
    });
    combined_components.add("DemoMask", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMask",
            DemoMask {}
        }
    });
    combined_components.add("DemoMenubar", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMenubar",
            DemoMenubar {}
        }
    });
    combined_components.add("DemoMenubarRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMenubarRtl",
            DemoMenubarRtl {}
        }
    });
    combined_components.add("DemoMessage", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMessage",
            DemoMessage {}
        }
    });
    combined_components.add("DemoMessageActions", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMessageActions",
            DemoMessageActions {}
        }
    });
    combined_components.add("DemoMessageAttachment", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMessageAttachment",
            DemoMessageAttachment {}
        }
    });
    combined_components.add("DemoMessageAvatar", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMessageAvatar",
            DemoMessageAvatar {}
        }
    });
    combined_components.add("DemoMessageGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMessageGroup",
            DemoMessageGroup {}
        }
    });
    combined_components.add("DemoMessageHeaderFooter", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMessageHeaderFooter",
            DemoMessageHeaderFooter {}
        }
    });
    combined_components.add("DemoMultiSelect", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMultiSelect",
            DemoMultiSelect {}
        }
    });
    combined_components.add("DemoMultiSelectAlign", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMultiSelectAlign",
            DemoMultiSelectAlign {}
        }
    });
    combined_components.add("DemoMultiSelectScrollable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoMultiSelectScrollable",
            DemoMultiSelectScrollable {}
        }
    });
    combined_components.add("DemoNavigationMenu", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoNavigationMenu",
            DemoNavigationMenu {}
        }
    });
    combined_components.add("DemoNavigationMenuComplex", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoNavigationMenuComplex",
            DemoNavigationMenuComplex {}
        }
    });
    combined_components.add("DemoNavigationMenuRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoNavigationMenuRtl",
            DemoNavigationMenuRtl {}
        }
    });
    combined_components.add("DemoPagination", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoPagination",
            DemoPagination {}
        }
    });
    combined_components.add("DemoPopover", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoPopover",
            DemoPopover {}
        }
    });
    combined_components.add("DemoPressable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoPressable",
            DemoPressable {}
        }
    });
    combined_components.add("DemoProgress", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoProgress",
            DemoProgress {}
        }
    });
    combined_components.add("DemoRadioButton", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoRadioButton",
            DemoRadioButton {}
        }
    });
    combined_components.add("DemoRadioButtonCustom", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoRadioButtonCustom",
            DemoRadioButtonCustom {}
        }
    });
    combined_components.add("DemoRadioButtonGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoRadioButtonGroup",
            DemoRadioButtonGroup {}
        }
    });
    combined_components.add("DemoRadioButtonGroupRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoRadioButtonGroupRtl",
            DemoRadioButtonGroupRtl {}
        }
    });
    combined_components.add("DemoRadioGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoRadioGroup",
            DemoRadioGroup {}
        }
    });
    combined_components.add("DemoScrollArea", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoScrollArea",
            DemoScrollArea {}
        }
    });
    combined_components.add("DemoScrollAreaHorizontal", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoScrollAreaHorizontal",
            DemoScrollAreaHorizontal {}
        }
    });
    combined_components.add("DemoScrollAreaRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoScrollAreaRtl",
            DemoScrollAreaRtl {}
        }
    });
    combined_components.add("DemoSelect", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSelect",
            DemoSelect {}
        }
    });
    combined_components.add("DemoSelectNativeGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSelectNativeGroup",
            DemoSelectNativeGroup {}
        }
    });
    combined_components.add("DemoSelectRtl", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSelectRtl",
            DemoSelectRtl {}
        }
    });
    combined_components.add("DemoSelectScrollable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSelectScrollable",
            DemoSelectScrollable {}
        }
    });
    combined_components.add("DemoSeparator", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSeparator",
            DemoSeparator {}
        }
    });
    combined_components.add("DemoSheet", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSheet",
            DemoSheet {}
        }
    });
    combined_components.add("DemoShimmer", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoShimmer",
            DemoShimmer {}
        }
    });
    combined_components.add("DemoSkeleton", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSkeleton",
            DemoSkeleton {}
        }
    });
    combined_components.add("DemoSkeletonAvatar", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSkeletonAvatar",
            DemoSkeletonAvatar {}
        }
    });
    combined_components.add("DemoSkeletonForm", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSkeletonForm",
            DemoSkeletonForm {}
        }
    });
    combined_components.add("DemoSkeletonImage", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSkeletonImage",
            DemoSkeletonImage {}
        }
    });
    combined_components.add("DemoSkeletonTable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSkeletonTable",
            DemoSkeletonTable {}
        }
    });
    combined_components.add("DemoSkeletonText", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSkeletonText",
            DemoSkeletonText {}
        }
    });
    combined_components.add("DemoSlider", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSlider",
            DemoSlider {}
        }
    });
    combined_components.add("DemoSonner", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSonner",
            DemoSonner {}
        }
    });
    combined_components.add("DemoSonnerPositions", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSonnerPositions",
            DemoSonnerPositions {}
        }
    });
    combined_components.add("DemoSonnerVariants", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSonnerVariants",
            DemoSonnerVariants {}
        }
    });
    combined_components.add("DemoSpinner", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSpinner",
            DemoSpinner {}
        }
    });
    combined_components.add("DemoSpinnerButton", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSpinnerButton",
            DemoSpinnerButton {}
        }
    });
    combined_components.add("DemoStatus", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoStatus",
            DemoStatus {}
        }
    });
    combined_components.add("DemoStatusVariants", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoStatusVariants",
            DemoStatusVariants {}
        }
    });
    combined_components.add("DemoStepper", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoStepper",
            DemoStepper {}
        }
    });
    combined_components.add("DemoStepperControlled", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoStepperControlled",
            DemoStepperControlled {}
        }
    });
    combined_components.add("DemoStepperVertical", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoStepperVertical",
            DemoStepperVertical {}
        }
    });
    combined_components.add("DemoSwitch", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoSwitch",
            DemoSwitch {}
        }
    });
    combined_components.add("DemoTable", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoTable",
            DemoTable {}
        }
    });
    combined_components.add("DemoTabs", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoTabs",
            DemoTabs {}
        }
    });
    combined_components.add("DemoTextarea", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoTextarea",
            DemoTextarea {}
        }
    });
    combined_components.add("DemoThemeToggle", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoThemeToggle",
            DemoThemeToggle {}
        }
    });
    combined_components.add("DemoToast", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoToast",
            DemoToast {}
        }
    });
    combined_components.add("DemoToastVariants", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoToastVariants",
            DemoToastVariants {}
        }
    });
    combined_components.add("DemoToggle", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoToggle",
            DemoToggle {}
        }
    });
    combined_components.add("DemoToggleGroup", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoToggleGroup",
            DemoToggleGroup {}
        }
    });
    combined_components.add("DemoToolbar", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoToolbar",
            DemoToolbar {}
        }
    });
    combined_components.add("DemoTooltip", |_| rsx! {
        StaticDemoWrapper {
            demo_name: "DemoTooltip",
            DemoTooltip {}
        }
    });
    combined_components.add("InstallAccordion", |_| rsx! {
        StaticInstallWrapper {
            install_name: "accordion",
            demo_name: "demo_accordion",
            raw_code: include_str!("../../app_crates/registry/src/ui/accordion.rs"),
        }
    });
    combined_components.add("InstallAlert", |_| rsx! {
        StaticInstallWrapper {
            install_name: "alert",
            demo_name: "demo_alert",
            raw_code: include_str!("../../app_crates/registry/src/ui/alert.rs"),
        }
    });
    combined_components.add("InstallAlertDialog", |_| rsx! {
        StaticInstallWrapper {
            install_name: "alert-dialog",
            demo_name: "demo_alert_dialog",
            raw_code: include_str!("../../app_crates/registry/src/ui/alert_dialog.rs"),
        }
    });
    combined_components.add("InstallAnimate", |_| rsx! {
        StaticInstallWrapper {
            install_name: "animate",
            demo_name: "demo_animate",
            raw_code: include_str!("../../app_crates/registry/src/ui/animate.rs"),
        }
    });
    combined_components.add("InstallAnimateGroup", |_| rsx! {
        StaticInstallWrapper {
            install_name: "animate-group",
            demo_name: "demo_animate_group",
            raw_code: include_str!("../../app_crates/registry/src/ui/animate.rs"),
        }
    });
    combined_components.add("InstallAspectRatio", |_| rsx! {
        StaticInstallWrapper {
            install_name: "aspect-ratio",
            demo_name: "demo_aspect_ratio",
            raw_code: include_str!("../../app_crates/registry/src/ui/aspect_ratio.rs"),
        }
    });
    combined_components.add("InstallAttachment", |_| rsx! {
        StaticInstallWrapper {
            install_name: "attachment",
            demo_name: "demo_attachment",
            raw_code: include_str!("../../app_crates/registry/src/ui/attachment.rs"),
        }
    });
    combined_components.add("InstallAutoForm", |_| rsx! {
        StaticInstallWrapper {
            install_name: "auto-form",
            demo_name: "demo_auto_form",
            raw_code: include_str!("../../app_crates/registry/src/ui/auto_form.rs"),
        }
    });
    combined_components.add("InstallAvatar", |_| rsx! {
        StaticInstallWrapper {
            install_name: "avatar",
            demo_name: "demo_avatar",
            raw_code: include_str!("../../app_crates/registry/src/ui/avatar.rs"),
        }
    });
    combined_components.add("InstallBadge", |_| rsx! {
        StaticInstallWrapper {
            install_name: "badge",
            demo_name: "demo_badge",
            raw_code: include_str!("../../app_crates/registry/src/ui/badge.rs"),
        }
    });
    combined_components.add("InstallBentoGrid", |_| rsx! {
        StaticInstallWrapper {
            install_name: "bento-grid",
            demo_name: "demo_bento_grid",
            raw_code: include_str!("../../app_crates/registry/src/ui/bento_grid.rs"),
        }
    });
    combined_components.add("InstallBottomNav", |_| rsx! {
        StaticInstallWrapper {
            install_name: "bottom-nav",
            demo_name: "demo_bottom_nav",
            raw_code: include_str!("../../app_crates/registry/src/ui/bottom_nav.rs"),
        }
    });
    combined_components.add("InstallBreadcrumb", |_| rsx! {
        StaticInstallWrapper {
            install_name: "breadcrumb",
            demo_name: "demo_breadcrumb",
            raw_code: include_str!("../../app_crates/registry/src/ui/breadcrumb.rs"),
        }
    });
    combined_components.add("InstallBubble", |_| rsx! {
        StaticInstallWrapper {
            install_name: "bubble",
            demo_name: "demo_bubble",
            raw_code: include_str!("../../app_crates/registry/src/ui/bubble.rs"),
        }
    });
    combined_components.add("InstallButton", |_| rsx! {
        StaticInstallWrapper {
            install_name: "button",
            demo_name: "demo_button",
            raw_code: include_str!("../../app_crates/registry/src/ui/button.rs"),
        }
    });
    combined_components.add("InstallButtonAction", |_| rsx! {
        StaticInstallWrapper {
            install_name: "button-action",
            demo_name: "demo_button_action",
            raw_code: include_str!("../../app_crates/registry/src/ui/button_action.rs"),
        }
    });
    combined_components.add("InstallButtonGroup", |_| rsx! {
        StaticInstallWrapper {
            install_name: "button-group",
            demo_name: "demo_button_group",
            raw_code: include_str!("../../app_crates/registry/src/ui/button_group.rs"),
        }
    });
    combined_components.add("InstallCallout", |_| rsx! {
        StaticInstallWrapper {
            install_name: "callout",
            demo_name: "demo_callout",
            raw_code: include_str!("../../app_crates/registry/src/ui/callout.rs"),
        }
    });
    combined_components.add("InstallCard", |_| rsx! {
        StaticInstallWrapper {
            install_name: "card",
            demo_name: "demo_card",
            raw_code: include_str!("../../app_crates/registry/src/ui/card.rs"),
        }
    });
    combined_components.add("InstallCardCarousel", |_| rsx! {
        StaticInstallWrapper {
            install_name: "card-carousel",
            demo_name: "demo_card_carousel",
            raw_code: include_str!("../../app_crates/registry/src/ui/card_carousel.rs"),
        }
    });
    combined_components.add("InstallCarousel", |_| rsx! {
        StaticInstallWrapper {
            install_name: "carousel",
            demo_name: "demo_carousel",
            raw_code: include_str!("../../app_crates/registry/src/ui/carousel.rs"),
        }
    });
    combined_components.add("InstallChat", |_| rsx! {
        StaticInstallWrapper {
            install_name: "chat",
            demo_name: "demo_chat",
            raw_code: include_str!("../../app_crates/registry/src/ui/chat.rs"),
        }
    });
    combined_components.add("InstallCheckbox", |_| rsx! {
        StaticInstallWrapper {
            install_name: "checkbox",
            demo_name: "demo_checkbox",
            raw_code: include_str!("../../app_crates/registry/src/ui/checkbox.rs"),
        }
    });
    combined_components.add("InstallChips", |_| rsx! {
        StaticInstallWrapper {
            install_name: "chips",
            demo_name: "demo_chips",
            raw_code: include_str!("../../app_crates/registry/src/ui/chips.rs"),
        }
    });
    combined_components.add("InstallCollapsible", |_| rsx! {
        StaticInstallWrapper {
            install_name: "collapsible",
            demo_name: "demo_collapsible",
            raw_code: include_str!("../../app_crates/registry/src/ui/collapsible.rs"),
        }
    });
    combined_components.add("InstallCombobox", |_| rsx! {
        StaticInstallWrapper {
            install_name: "combobox",
            demo_name: "demo_combobox",
            raw_code: include_str!("../../app_crates/registry/src/ui/command.rs"),
        }
    });
    combined_components.add("InstallCommand", |_| rsx! {
        StaticInstallWrapper {
            install_name: "command",
            demo_name: "demo_command",
            raw_code: include_str!("../../app_crates/registry/src/ui/command.rs"),
        }
    });
    combined_components.add("InstallContextMenu", |_| rsx! {
        StaticInstallWrapper {
            install_name: "context-menu",
            demo_name: "demo_context_menu",
            raw_code: include_str!("../../app_crates/registry/src/ui/context_menu.rs"),
        }
    });
    combined_components.add("InstallDataGrid", |_| rsx! {
        StaticInstallWrapper {
            install_name: "data-grid",
            demo_name: "demo_data_grid",
            raw_code: include_str!("../../app_crates/registry/src/ui/data_grid.rs"),
        }
    });
    combined_components.add("InstallDataTable", |_| rsx! {
        StaticInstallWrapper {
            install_name: "data-table",
            demo_name: "demo_data_table",
            raw_code: include_str!("../../app_crates/registry/src/ui/data_table.rs"),
        }
    });
    combined_components.add("InstallDatePicker", |_| rsx! {
        StaticInstallWrapper {
            install_name: "date-picker",
            demo_name: "demo_date_picker",
            raw_code: include_str!("../../app_crates/registry/src/ui/date_picker.rs"),
        }
    });
    combined_components.add("InstallDialog", |_| rsx! {
        StaticInstallWrapper {
            install_name: "dialog",
            demo_name: "demo_dialog",
            raw_code: include_str!("../../app_crates/registry/src/ui/dialog.rs"),
        }
    });
    combined_components.add("InstallDirectionProvider", |_| rsx! {
        StaticInstallWrapper {
            install_name: "direction-provider",
            demo_name: "demo_direction_provider",
            raw_code: include_str!("../../app_crates/registry/src/ui/direction_provider.rs"),
        }
    });
    combined_components.add("InstallDragAndDrop", |_| rsx! {
        StaticInstallWrapper {
            install_name: "drag-and-drop",
            demo_name: "demo_drag_and_drop",
            raw_code: include_str!("../../app_crates/registry/src/ui/drag_and_drop.rs"),
        }
    });
    combined_components.add("InstallDrawer", |_| rsx! {
        StaticInstallWrapper {
            install_name: "drawer",
            demo_name: "demo_drawer",
            raw_code: include_str!("../../app_crates/registry/src/ui/drawer.rs"),
        }
    });
    combined_components.add("InstallDropdownMenu", |_| rsx! {
        StaticInstallWrapper {
            install_name: "dropdown-menu",
            demo_name: "demo_dropdown_menu",
            raw_code: include_str!("../../app_crates/registry/src/ui/dropdown_menu.rs"),
        }
    });
    combined_components.add("InstallDropzone", |_| rsx! {
        StaticInstallWrapper {
            install_name: "dropzone",
            demo_name: "demo_dropzone",
            raw_code: include_str!("../../app_crates/registry/src/ui/dropzone.rs"),
        }
    });
    combined_components.add("InstallEmpty", |_| rsx! {
        StaticInstallWrapper {
            install_name: "empty",
            demo_name: "demo_empty",
            raw_code: include_str!("../../app_crates/registry/src/ui/empty.rs"),
        }
    });
    combined_components.add("InstallExpandable", |_| rsx! {
        StaticInstallWrapper {
            install_name: "expandable",
            demo_name: "demo_expandable",
            raw_code: include_str!("../../app_crates/registry/src/ui/expandable.rs"),
        }
    });
    combined_components.add("InstallFaqTransition", |_| rsx! {
        StaticInstallWrapper {
            install_name: "faq-transition",
            demo_name: "demo_faq_transition",
            raw_code: include_str!("../../app_crates/registry/src/ui/faq_transition.rs"),
        }
    });
    combined_components.add("InstallField", |_| rsx! {
        StaticInstallWrapper {
            install_name: "field",
            demo_name: "demo_field",
            raw_code: include_str!("../../app_crates/registry/src/ui/field.rs"),
        }
    });
    combined_components.add("InstallForm", |_| rsx! {
        StaticInstallWrapper {
            install_name: "form",
            demo_name: "demo_form",
            raw_code: include_str!("../../app_crates/registry/src/ui/form.rs"),
        }
    });
    combined_components.add("InstallHoverCard", |_| rsx! {
        StaticInstallWrapper {
            install_name: "hover-card",
            demo_name: "demo_hover_card",
            raw_code: include_str!("../../app_crates/registry/src/ui/hover_card.rs"),
        }
    });
    combined_components.add("InstallImage", |_| rsx! {
        StaticInstallWrapper {
            install_name: "image",
            demo_name: "demo_image",
            raw_code: include_str!("../../app_crates/registry/src/ui/image.rs"),
        }
    });
    combined_components.add("InstallInput", |_| rsx! {
        StaticInstallWrapper {
            install_name: "input",
            demo_name: "demo_input",
            raw_code: include_str!("../../app_crates/registry/src/ui/input.rs"),
        }
    });
    combined_components.add("InstallInputGroup", |_| rsx! {
        StaticInstallWrapper {
            install_name: "input-group",
            demo_name: "demo_input_group",
            raw_code: include_str!("../../app_crates/registry/src/ui/input_group.rs"),
        }
    });
    combined_components.add("InstallInputOtp", |_| rsx! {
        StaticInstallWrapper {
            install_name: "input-otp",
            demo_name: "demo_input_otp",
            raw_code: include_str!("../../app_crates/registry/src/ui/input_otp.rs"),
        }
    });
    combined_components.add("InstallInputPhone", |_| rsx! {
        StaticInstallWrapper {
            install_name: "input-phone",
            demo_name: "demo_input_phone",
            raw_code: include_str!("../../app_crates/registry/src/ui/input_phone.rs"),
        }
    });
    combined_components.add("InstallInputPrompt", |_| rsx! {
        StaticInstallWrapper {
            install_name: "input-prompt",
            demo_name: "demo_input_prompt",
            raw_code: include_str!("../../app_crates/registry/src/ui/input_prompt.rs"),
        }
    });
    combined_components.add("InstallItem", |_| rsx! {
        StaticInstallWrapper {
            install_name: "item",
            demo_name: "demo_item",
            raw_code: include_str!("../../app_crates/registry/src/ui/item.rs"),
        }
    });
    combined_components.add("InstallKbd", |_| rsx! {
        StaticInstallWrapper {
            install_name: "kbd",
            demo_name: "demo_kbd",
            raw_code: include_str!("../../app_crates/registry/src/ui/kbd.rs"),
        }
    });
    combined_components.add("InstallLabel", |_| rsx! {
        StaticInstallWrapper {
            install_name: "label",
            demo_name: "demo_label",
            raw_code: include_str!("../../app_crates/registry/src/ui/label.rs"),
        }
    });
    combined_components.add("InstallMarker", |_| rsx! {
        StaticInstallWrapper {
            install_name: "marker",
            demo_name: "demo_marker",
            raw_code: include_str!("../../app_crates/registry/src/ui/marker.rs"),
        }
    });
    combined_components.add("InstallMarquee", |_| rsx! {
        StaticInstallWrapper {
            install_name: "marquee",
            demo_name: "demo_marquee",
            raw_code: include_str!("../../app_crates/registry/src/ui/marquee.rs"),
        }
    });
    combined_components.add("InstallMask", |_| rsx! {
        StaticInstallWrapper {
            install_name: "mask",
            demo_name: "demo_mask",
            raw_code: include_str!("../../app_crates/registry/src/ui/mask.rs"),
        }
    });
    combined_components.add("InstallMenubar", |_| rsx! {
        StaticInstallWrapper {
            install_name: "menubar",
            demo_name: "demo_menubar",
            raw_code: include_str!("../../app_crates/registry/src/ui/menubar.rs"),
        }
    });
    combined_components.add("InstallMessage", |_| rsx! {
        StaticInstallWrapper {
            install_name: "message",
            demo_name: "demo_message",
            raw_code: include_str!("../../app_crates/registry/src/ui/message.rs"),
        }
    });
    combined_components.add("InstallMultiSelect", |_| rsx! {
        StaticInstallWrapper {
            install_name: "multi-select",
            demo_name: "demo_multi_select",
            raw_code: include_str!("../../app_crates/registry/src/ui/multi_select.rs"),
        }
    });
    combined_components.add("InstallNavigationMenu", |_| rsx! {
        StaticInstallWrapper {
            install_name: "navigation-menu",
            demo_name: "demo_navigation_menu",
            raw_code: include_str!("../../app_crates/registry/src/ui/navigation_menu.rs"),
        }
    });
    combined_components.add("InstallPagination", |_| rsx! {
        StaticInstallWrapper {
            install_name: "pagination",
            demo_name: "demo_pagination",
            raw_code: include_str!("../../app_crates/registry/src/ui/pagination.rs"),
        }
    });
    combined_components.add("InstallPopover", |_| rsx! {
        StaticInstallWrapper {
            install_name: "popover",
            demo_name: "demo_popover",
            raw_code: include_str!("../../app_crates/registry/src/ui/popover.rs"),
        }
    });
    combined_components.add("InstallPressable", |_| rsx! {
        StaticInstallWrapper {
            install_name: "pressable",
            demo_name: "demo_pressable",
            raw_code: include_str!("../../app_crates/registry/src/ui/pressable.rs"),
        }
    });
    combined_components.add("InstallProgress", |_| rsx! {
        StaticInstallWrapper {
            install_name: "progress",
            demo_name: "demo_progress",
            raw_code: include_str!("../../app_crates/registry/src/ui/progress.rs"),
        }
    });
    combined_components.add("InstallRadioButton", |_| rsx! {
        StaticInstallWrapper {
            install_name: "radio-button",
            demo_name: "demo_radio_button",
            raw_code: include_str!("../../app_crates/registry/src/ui/radio_button.rs"),
        }
    });
    combined_components.add("InstallRadioButtonGroup", |_| rsx! {
        StaticInstallWrapper {
            install_name: "radio-button-group",
            demo_name: "demo_radio_button_group",
            raw_code: include_str!("../../app_crates/registry/src/ui/radio_button_group.rs"),
        }
    });
    combined_components.add("InstallRadioGroup", |_| rsx! {
        StaticInstallWrapper {
            install_name: "radio-group",
            demo_name: "demo_radio_group",
            raw_code: include_str!("../../app_crates/registry/src/ui/radio_group.rs"),
        }
    });
    combined_components.add("InstallScrollArea", |_| rsx! {
        StaticInstallWrapper {
            install_name: "scroll-area",
            demo_name: "demo_scroll_area",
            raw_code: include_str!("../../app_crates/registry/src/ui/scroll_area.rs"),
        }
    });
    combined_components.add("InstallSelect", |_| rsx! {
        StaticInstallWrapper {
            install_name: "select",
            demo_name: "demo_select",
            raw_code: include_str!("../../app_crates/registry/src/ui/select.rs"),
        }
    });
    combined_components.add("InstallSelectNative", |_| rsx! {
        StaticInstallWrapper {
            install_name: "select-native",
            demo_name: "demo_select_native",
            raw_code: include_str!("../../app_crates/registry/src/ui/select_native.rs"),
        }
    });
    combined_components.add("InstallSeparator", |_| rsx! {
        StaticInstallWrapper {
            install_name: "separator",
            demo_name: "demo_separator",
            raw_code: include_str!("../../app_crates/registry/src/ui/separator.rs"),
        }
    });
    combined_components.add("InstallSheet", |_| rsx! {
        StaticInstallWrapper {
            install_name: "sheet",
            demo_name: "demo_sheet",
            raw_code: include_str!("../../app_crates/registry/src/ui/sheet.rs"),
        }
    });
    combined_components.add("InstallShimmer", |_| rsx! {
        StaticInstallWrapper {
            install_name: "shimmer",
            demo_name: "demo_shimmer",
            raw_code: include_str!("../../app_crates/registry/src/ui/shimmer.rs"),
        }
    });
    combined_components.add("InstallSkeleton", |_| rsx! {
        StaticInstallWrapper {
            install_name: "skeleton",
            demo_name: "demo_skeleton",
            raw_code: include_str!("../../app_crates/registry/src/ui/skeleton.rs"),
        }
    });
    combined_components.add("InstallSlider", |_| rsx! {
        StaticInstallWrapper {
            install_name: "slider",
            demo_name: "demo_slider",
            raw_code: include_str!("../../app_crates/registry/src/ui/slider.rs"),
        }
    });
    combined_components.add("InstallSonner", |_| rsx! {
        StaticInstallWrapper {
            install_name: "sonner",
            demo_name: "demo_sonner",
            raw_code: include_str!("../../app_crates/registry/src/ui/sonner.rs"),
        }
    });
    combined_components.add("InstallSpinner", |_| rsx! {
        StaticInstallWrapper {
            install_name: "spinner",
            demo_name: "demo_spinner",
            raw_code: include_str!("../../app_crates/registry/src/ui/spinner.rs"),
        }
    });
    combined_components.add("InstallStatus", |_| rsx! {
        StaticInstallWrapper {
            install_name: "status",
            demo_name: "demo_status",
            raw_code: include_str!("../../app_crates/registry/src/ui/status.rs"),
        }
    });
    combined_components.add("InstallStepper", |_| rsx! {
        StaticInstallWrapper {
            install_name: "stepper",
            demo_name: "demo_stepper",
            raw_code: include_str!("../../app_crates/registry/src/ui/stepper.rs"),
        }
    });
    combined_components.add("InstallSwitch", |_| rsx! {
        StaticInstallWrapper {
            install_name: "switch",
            demo_name: "demo_switch",
            raw_code: include_str!("../../app_crates/registry/src/ui/switch.rs"),
        }
    });
    combined_components.add("InstallTable", |_| rsx! {
        StaticInstallWrapper {
            install_name: "table",
            demo_name: "demo_table",
            raw_code: include_str!("../../app_crates/registry/src/ui/table.rs"),
        }
    });
    combined_components.add("InstallTabs", |_| rsx! {
        StaticInstallWrapper {
            install_name: "tabs",
            demo_name: "demo_tabs",
            raw_code: include_str!("../../app_crates/registry/src/ui/tabs.rs"),
        }
    });
    combined_components.add("InstallTextarea", |_| rsx! {
        StaticInstallWrapper {
            install_name: "textarea",
            demo_name: "demo_textarea",
            raw_code: include_str!("../../app_crates/registry/src/ui/textarea.rs"),
        }
    });
    combined_components.add("InstallThemeToggle", |_| rsx! {
        StaticInstallWrapper {
            install_name: "theme-toggle",
            demo_name: "demo_theme_toggle",
            raw_code: include_str!("../../app_crates/registry/src/ui/theme_toggle.rs"),
        }
    });
    combined_components.add("InstallToast", |_| rsx! {
        StaticInstallWrapper {
            install_name: "toast",
            demo_name: "demo_toast",
            raw_code: include_str!("../../app_crates/registry/src/ui/toast_custom/mod.rs"),
        }
    });
    combined_components.add("InstallToggle", |_| rsx! {
        StaticInstallWrapper {
            install_name: "toggle",
            demo_name: "demo_toggle",
            raw_code: include_str!("../../app_crates/registry/src/ui/toggle.rs"),
        }
    });
    combined_components.add("InstallToggleGroup", |_| rsx! {
        StaticInstallWrapper {
            install_name: "toggle-group",
            demo_name: "demo_toggle_group",
            raw_code: include_str!("../../app_crates/registry/src/ui/toggle_group.rs"),
        }
    });
    combined_components.add("InstallToolbar", |_| rsx! {
        StaticInstallWrapper {
            install_name: "toolbar",
            demo_name: "demo_toolbar",
            raw_code: include_str!("../../app_crates/registry/src/ui/toolbar.rs"),
        }
    });
    combined_components.add("InstallTooltip", |_| rsx! {
        StaticInstallWrapper {
            install_name: "tooltip",
            demo_name: "demo_tooltip",
            raw_code: include_str!("../../app_crates/registry/src/ui/tooltip.rs"),
        }
    });
    combined_components
}

pub static ACCORDION: RegistryEntry = RegistryEntry {
    slug: "accordion",
    raw: include_str!("../../public/docs/accordion.md"),
    tags: &[],
};

pub static ALERT: RegistryEntry = RegistryEntry {
    slug: "alert",
    raw: include_str!("../../public/docs/alert.md"),
    tags: &[],
};

pub static ALERT_DIALOG: RegistryEntry = RegistryEntry {
    slug: "alert-dialog",
    raw: include_str!("../../public/docs/alert_dialog.md"),
    tags: &[],
};

pub static ANIMATE: RegistryEntry = RegistryEntry {
    slug: "animate",
    raw: include_str!("../../public/docs/animate.md"),
    tags: &[],
};

pub static ANIMATE_GROUP: RegistryEntry = RegistryEntry {
    slug: "animate-group",
    raw: include_str!("../../public/docs/animate_group.md"),
    tags: &[],
};

pub static ASPECT_RATIO: RegistryEntry = RegistryEntry {
    slug: "aspect-ratio",
    raw: include_str!("../../public/docs/aspect_ratio.md"),
    tags: &[],
};

pub static ATTACHMENT: RegistryEntry = RegistryEntry {
    slug: "attachment",
    raw: include_str!("../../public/docs/attachment.md"),
    tags: &[],
};

pub static AUTO_FORM: RegistryEntry = RegistryEntry {
    slug: "auto-form",
    raw: include_str!("../../public/docs/auto_form.md"),
    tags: &[],
};

pub static AVATAR: RegistryEntry = RegistryEntry {
    slug: "avatar",
    raw: include_str!("../../public/docs/avatar.md"),
    tags: &[],
};

pub static BADGE: RegistryEntry = RegistryEntry {
    slug: "badge",
    raw: include_str!("../../public/docs/badge.md"),
    tags: &[],
};

pub static BENTO_GRID: RegistryEntry = RegistryEntry {
    slug: "bento-grid",
    raw: include_str!("../../public/docs/bento_grid.md"),
    tags: &[],
};

pub static BOTTOM_NAV: RegistryEntry = RegistryEntry {
    slug: "bottom-nav",
    raw: include_str!("../../public/docs/bottom_nav.md"),
    tags: &[],
};

pub static BREADCRUMB: RegistryEntry = RegistryEntry {
    slug: "breadcrumb",
    raw: include_str!("../../public/docs/breadcrumb.md"),
    tags: &[],
};

pub static BUBBLE: RegistryEntry = RegistryEntry {
    slug: "bubble",
    raw: include_str!("../../public/docs/bubble.md"),
    tags: &[],
};

pub static BUTTON: RegistryEntry = RegistryEntry {
    slug: "button",
    raw: include_str!("../../public/docs/button.md"),
    tags: &[],
};

pub static BUTTON_ACTION: RegistryEntry = RegistryEntry {
    slug: "button-action",
    raw: include_str!("../../public/docs/button_action.md"),
    tags: &[],
};

pub static BUTTON_GROUP: RegistryEntry = RegistryEntry {
    slug: "button-group",
    raw: include_str!("../../public/docs/button_group.md"),
    tags: &[],
};

pub static CALLOUT: RegistryEntry = RegistryEntry {
    slug: "callout",
    raw: include_str!("../../public/docs/callout.md"),
    tags: &[],
};

pub static CARD: RegistryEntry = RegistryEntry {
    slug: "card",
    raw: include_str!("../../public/docs/card.md"),
    tags: &[],
};

pub static CARD_CAROUSEL: RegistryEntry = RegistryEntry {
    slug: "card-carousel",
    raw: include_str!("../../public/docs/card_carousel.md"),
    tags: &[],
};

pub static CAROUSEL: RegistryEntry = RegistryEntry {
    slug: "carousel",
    raw: include_str!("../../public/docs/carousel.md"),
    tags: &[],
};

pub static CHANGELOG: RegistryEntry = RegistryEntry {
    slug: "changelog",
    raw: include_str!("../../public/docs/changelog.md"),
    tags: &[],
};

pub static CHAT: RegistryEntry = RegistryEntry {
    slug: "chat",
    raw: include_str!("../../public/docs/chat.md"),
    tags: &[],
};

pub static CHECKBOX: RegistryEntry = RegistryEntry {
    slug: "checkbox",
    raw: include_str!("../../public/docs/checkbox.md"),
    tags: &[],
};

pub static CHIPS: RegistryEntry = RegistryEntry {
    slug: "chips",
    raw: include_str!("../../public/docs/chips.md"),
    tags: &[],
};

pub static COLLAPSIBLE: RegistryEntry = RegistryEntry {
    slug: "collapsible",
    raw: include_str!("../../public/docs/collapsible.md"),
    tags: &[],
};

pub static COMBOBOX: RegistryEntry = RegistryEntry {
    slug: "combobox",
    raw: include_str!("../../public/docs/combobox.md"),
    tags: &[],
};

pub static COMMAND: RegistryEntry = RegistryEntry {
    slug: "command",
    raw: include_str!("../../public/docs/command.md"),
    tags: &[],
};

pub static CONTEXT_MENU: RegistryEntry = RegistryEntry {
    slug: "context-menu",
    raw: include_str!("../../public/docs/context_menu.md"),
    tags: &[],
};

pub static DATA_GRID: RegistryEntry = RegistryEntry {
    slug: "data-grid",
    raw: include_str!("../../public/docs/data_grid.md"),
    tags: &[],
};

pub static DATA_TABLE: RegistryEntry = RegistryEntry {
    slug: "data-table",
    raw: include_str!("../../public/docs/data_table.md"),
    tags: &[],
};

pub static DATE_PICKER: RegistryEntry = RegistryEntry {
    slug: "date-picker",
    raw: include_str!("../../public/docs/date_picker.md"),
    tags: &[],
};

pub static DIALOG: RegistryEntry = RegistryEntry {
    slug: "dialog",
    raw: include_str!("../../public/docs/dialog.md"),
    tags: &[],
};

pub static DIRECTION_PROVIDER: RegistryEntry = RegistryEntry {
    slug: "direction-provider",
    raw: include_str!("../../public/docs/direction_provider.md"),
    tags: &[],
};

pub static DRAG_AND_DROP: RegistryEntry = RegistryEntry {
    slug: "drag-and-drop",
    raw: include_str!("../../public/docs/drag_and_drop.md"),
    tags: &[],
};

pub static DRAWER: RegistryEntry = RegistryEntry {
    slug: "drawer",
    raw: include_str!("../../public/docs/drawer.md"),
    tags: &[],
};

pub static DROPDOWN_MENU: RegistryEntry = RegistryEntry {
    slug: "dropdown-menu",
    raw: include_str!("../../public/docs/dropdown_menu.md"),
    tags: &[],
};

pub static DROPZONE: RegistryEntry = RegistryEntry {
    slug: "dropzone",
    raw: include_str!("../../public/docs/dropzone.md"),
    tags: &[],
};

pub static EMPTY: RegistryEntry = RegistryEntry {
    slug: "empty",
    raw: include_str!("../../public/docs/empty.md"),
    tags: &[],
};

pub static EXPANDABLE: RegistryEntry = RegistryEntry {
    slug: "expandable",
    raw: include_str!("../../public/docs/expandable.md"),
    tags: &[],
};

pub static FAQ_TRANSITION: RegistryEntry = RegistryEntry {
    slug: "faq-transition",
    raw: include_str!("../../public/docs/faq_transition.md"),
    tags: &[],
};

pub static FIELD: RegistryEntry = RegistryEntry {
    slug: "field",
    raw: include_str!("../../public/docs/field.md"),
    tags: &[],
};

pub static FIGMA: RegistryEntry = RegistryEntry {
    slug: "figma",
    raw: include_str!("../../public/docs/figma.md"),
    tags: &[],
};

pub static FORM: RegistryEntry = RegistryEntry {
    slug: "form",
    raw: include_str!("../../public/docs/form.md"),
    tags: &[],
};

pub static HOVER_CARD: RegistryEntry = RegistryEntry {
    slug: "hover-card",
    raw: include_str!("../../public/docs/hover_card.md"),
    tags: &[],
};

pub static IMAGE: RegistryEntry = RegistryEntry {
    slug: "image",
    raw: include_str!("../../public/docs/image.md"),
    tags: &[],
};

pub static INPUT: RegistryEntry = RegistryEntry {
    slug: "input",
    raw: include_str!("../../public/docs/input.md"),
    tags: &[],
};

pub static INPUT_GROUP: RegistryEntry = RegistryEntry {
    slug: "input-group",
    raw: include_str!("../../public/docs/input_group.md"),
    tags: &[],
};

pub static INPUT_OTP: RegistryEntry = RegistryEntry {
    slug: "input-otp",
    raw: include_str!("../../public/docs/input_otp.md"),
    tags: &[],
};

pub static INPUT_PHONE: RegistryEntry = RegistryEntry {
    slug: "input-phone",
    raw: include_str!("../../public/docs/input_phone.md"),
    tags: &[],
};

pub static INPUT_PROMPT: RegistryEntry = RegistryEntry {
    slug: "input-prompt",
    raw: include_str!("../../public/docs/input_prompt.md"),
    tags: &[],
};

pub static INSTALLATION: RegistryEntry = RegistryEntry {
    slug: "installation",
    raw: include_str!("../../public/docs/installation.md"),
    tags: &[],
};

pub static INTRODUCTION: RegistryEntry = RegistryEntry {
    slug: "introduction",
    raw: include_str!("../../public/docs/introduction.md"),
    tags: &[],
};

pub static ITEM: RegistryEntry = RegistryEntry {
    slug: "item",
    raw: include_str!("../../public/docs/item.md"),
    tags: &[],
};

pub static KBD: RegistryEntry = RegistryEntry {
    slug: "kbd",
    raw: include_str!("../../public/docs/kbd.md"),
    tags: &[],
};

pub static LABEL: RegistryEntry = RegistryEntry {
    slug: "label",
    raw: include_str!("../../public/docs/label.md"),
    tags: &[],
};

pub static MARKER: RegistryEntry = RegistryEntry {
    slug: "marker",
    raw: include_str!("../../public/docs/marker.md"),
    tags: &[],
};

pub static MARQUEE: RegistryEntry = RegistryEntry {
    slug: "marquee",
    raw: include_str!("../../public/docs/marquee.md"),
    tags: &[],
};

pub static MASK: RegistryEntry = RegistryEntry {
    slug: "mask",
    raw: include_str!("../../public/docs/mask.md"),
    tags: &[],
};

pub static MENUBAR: RegistryEntry = RegistryEntry {
    slug: "menubar",
    raw: include_str!("../../public/docs/menubar.md"),
    tags: &[],
};

pub static MESSAGE: RegistryEntry = RegistryEntry {
    slug: "message",
    raw: include_str!("../../public/docs/message.md"),
    tags: &[],
};

pub static MULTI_SELECT: RegistryEntry = RegistryEntry {
    slug: "multi-select",
    raw: include_str!("../../public/docs/multi_select.md"),
    tags: &[],
};

pub static NAVIGATION_MENU: RegistryEntry = RegistryEntry {
    slug: "navigation-menu",
    raw: include_str!("../../public/docs/navigation_menu.md"),
    tags: &[],
};

pub static PAGINATION: RegistryEntry = RegistryEntry {
    slug: "pagination",
    raw: include_str!("../../public/docs/pagination.md"),
    tags: &[],
};

pub static POPOVER: RegistryEntry = RegistryEntry {
    slug: "popover",
    raw: include_str!("../../public/docs/popover.md"),
    tags: &[],
};

pub static PRESSABLE: RegistryEntry = RegistryEntry {
    slug: "pressable",
    raw: include_str!("../../public/docs/pressable.md"),
    tags: &[],
};

pub static PROGRESS: RegistryEntry = RegistryEntry {
    slug: "progress",
    raw: include_str!("../../public/docs/progress.md"),
    tags: &[],
};

pub static RTL: RegistryEntry = RegistryEntry {
    slug: "rtl",
    raw: include_str!("../../public/docs/rtl.md"),
    tags: &[],
};

pub static RADIO_BUTTON: RegistryEntry = RegistryEntry {
    slug: "radio-button",
    raw: include_str!("../../public/docs/radio_button.md"),
    tags: &[],
};

pub static RADIO_BUTTON_GROUP: RegistryEntry = RegistryEntry {
    slug: "radio-button-group",
    raw: include_str!("../../public/docs/radio_button_group.md"),
    tags: &[],
};

pub static RADIO_GROUP: RegistryEntry = RegistryEntry {
    slug: "radio-group",
    raw: include_str!("../../public/docs/radio-group.md"),
    tags: &[],
};

pub static SCROLL_AREA: RegistryEntry = RegistryEntry {
    slug: "scroll-area",
    raw: include_str!("../../public/docs/scroll_area.md"),
    tags: &[],
};

pub static SELECT: RegistryEntry = RegistryEntry {
    slug: "select",
    raw: include_str!("../../public/docs/select.md"),
    tags: &[],
};

pub static SELECT_NATIVE: RegistryEntry = RegistryEntry {
    slug: "select-native",
    raw: include_str!("../../public/docs/select_native.md"),
    tags: &[],
};

pub static SEPARATOR: RegistryEntry = RegistryEntry {
    slug: "separator",
    raw: include_str!("../../public/docs/separator.md"),
    tags: &[],
};

pub static SHEET: RegistryEntry = RegistryEntry {
    slug: "sheet",
    raw: include_str!("../../public/docs/sheet.md"),
    tags: &[],
};

pub static SHIMMER: RegistryEntry = RegistryEntry {
    slug: "shimmer",
    raw: include_str!("../../public/docs/shimmer.md"),
    tags: &[],
};

pub static SKELETON: RegistryEntry = RegistryEntry {
    slug: "skeleton",
    raw: include_str!("../../public/docs/skeleton.md"),
    tags: &[],
};

pub static SLIDER: RegistryEntry = RegistryEntry {
    slug: "slider",
    raw: include_str!("../../public/docs/slider.md"),
    tags: &[],
};

pub static SONNER: RegistryEntry = RegistryEntry {
    slug: "sonner",
    raw: include_str!("../../public/docs/sonner.md"),
    tags: &[],
};

pub static SPINNER: RegistryEntry = RegistryEntry {
    slug: "spinner",
    raw: include_str!("../../public/docs/spinner.md"),
    tags: &[],
};

pub static STATUS: RegistryEntry = RegistryEntry {
    slug: "status",
    raw: include_str!("../../public/docs/status.md"),
    tags: &[],
};

pub static STEPPER: RegistryEntry = RegistryEntry {
    slug: "stepper",
    raw: include_str!("../../public/docs/stepper.md"),
    tags: &[],
};

pub static SWITCH: RegistryEntry = RegistryEntry {
    slug: "switch",
    raw: include_str!("../../public/docs/switch.md"),
    tags: &[],
};

pub static TABLE: RegistryEntry = RegistryEntry {
    slug: "table",
    raw: include_str!("../../public/docs/table.md"),
    tags: &[],
};

pub static TABS: RegistryEntry = RegistryEntry {
    slug: "tabs",
    raw: include_str!("../../public/docs/tabs.md"),
    tags: &[],
};

pub static TEXTAREA: RegistryEntry = RegistryEntry {
    slug: "textarea",
    raw: include_str!("../../public/docs/textarea.md"),
    tags: &[],
};

pub static THEME_TOGGLE: RegistryEntry = RegistryEntry {
    slug: "theme-toggle",
    raw: include_str!("../../public/docs/theme_toggle.md"),
    tags: &[],
};

pub static TOAST: RegistryEntry = RegistryEntry {
    slug: "toast",
    raw: include_str!("../../public/docs/toast.md"),
    tags: &[],
};

pub static TOGGLE: RegistryEntry = RegistryEntry {
    slug: "toggle",
    raw: include_str!("../../public/docs/toggle.md"),
    tags: &[],
};

pub static TOGGLE_GROUP: RegistryEntry = RegistryEntry {
    slug: "toggle-group",
    raw: include_str!("../../public/docs/toggle_group.md"),
    tags: &[],
};

pub static TOOLBAR: RegistryEntry = RegistryEntry {
    slug: "toolbar",
    raw: include_str!("../../public/docs/toolbar.md"),
    tags: &[],
};

pub static TOOLTIP: RegistryEntry = RegistryEntry {
    slug: "tooltip",
    raw: include_str!("../../public/docs/tooltip.md"),
    tags: &[],
};

pub static USE_COPY_CLIPBOARD: RegistryEntry = RegistryEntry {
    slug: "use-copy-clipboard",
    raw: include_str!("../../public/docs/hooks/use_copy_clipboard.md"),
    tags: &[],
};

pub static USE_LOCK_BODY_SCROLL: RegistryEntry = RegistryEntry {
    slug: "use-lock-body-scroll",
    raw: include_str!("../../public/docs/hooks/use_lock_body_scroll.md"),
    tags: &[],
};

pub static USE_RANDOM: RegistryEntry = RegistryEntry {
    slug: "use-random",
    raw: include_str!("../../public/docs/hooks/use_random.md"),
    tags: &[],
};

pub static COMPONENT_REGISTRY: &[&RegistryEntry] = &[
    &ACCORDION,
    &ALERT,
    &ALERT_DIALOG,
    &ANIMATE,
    &ANIMATE_GROUP,
    &ASPECT_RATIO,
    &ATTACHMENT,
    &AUTO_FORM,
    &AVATAR,
    &BADGE,
    &BENTO_GRID,
    &BOTTOM_NAV,
    &BREADCRUMB,
    &BUBBLE,
    &BUTTON,
    &BUTTON_ACTION,
    &BUTTON_GROUP,
    &CALLOUT,
    &CARD,
    &CARD_CAROUSEL,
    &CAROUSEL,
    &CHAT,
    &CHECKBOX,
    &CHIPS,
    &COLLAPSIBLE,
    &COMBOBOX,
    &COMMAND,
    &CONTEXT_MENU,
    &DATA_GRID,
    &DATA_TABLE,
    &DATE_PICKER,
    &DIALOG,
    &DIRECTION_PROVIDER,
    &DRAG_AND_DROP,
    &DRAWER,
    &DROPDOWN_MENU,
    &DROPZONE,
    &EMPTY,
    &EXPANDABLE,
    &FAQ_TRANSITION,
    &FIELD,
    &FORM,
    &HOVER_CARD,
    &IMAGE,
    &INPUT,
    &INPUT_GROUP,
    &INPUT_OTP,
    &INPUT_PHONE,
    &INPUT_PROMPT,
    &ITEM,
    &KBD,
    &LABEL,
    &MARKER,
    &MARQUEE,
    &MASK,
    &MENUBAR,
    &MESSAGE,
    &MULTI_SELECT,
    &NAVIGATION_MENU,
    &PAGINATION,
    &POPOVER,
    &PRESSABLE,
    &PROGRESS,
    &RADIO_BUTTON,
    &RADIO_BUTTON_GROUP,
    &RADIO_GROUP,
    &SCROLL_AREA,
    &SELECT,
    &SELECT_NATIVE,
    &SEPARATOR,
    &SHEET,
    &SHIMMER,
    &SKELETON,
    &SLIDER,
    &SONNER,
    &SPINNER,
    &STATUS,
    &STEPPER,
    &SWITCH,
    &TABLE,
    &TABS,
    &TEXTAREA,
    &THEME_TOGGLE,
    &TOAST,
    &TOGGLE,
    &TOGGLE_GROUP,
    &TOOLBAR,
    &TOOLTIP,
];

pub static HOOKS_REGISTRY: &[&RegistryEntry] = &[
    &USE_COPY_CLIPBOARD,
    &USE_LOCK_BODY_SCROLL,
    &USE_RANDOM,
];

pub static GET_STARTED_REGISTRY: &[&RegistryEntry] = &[
    &CHANGELOG,
    &FIGMA,
    &INSTALLATION,
    &INTRODUCTION,
    &RTL,
];

fn find_in(registry: &[&'static RegistryEntry], slug: &str) -> Option<&'static RegistryEntry> {
    registry.iter().copied().find(|entry| entry.slug == slug)
}

fn prev_next_in(
    registry: &[&'static RegistryEntry],
    slug: &str,
) -> (Option<&'static RegistryEntry>, Option<&'static RegistryEntry>) {
    let pos = registry.iter().position(|entry| entry.slug == slug);
    match pos {
        None => (None, None),
        Some(i) => (
            if i > 0 { Some(registry[i - 1]) } else { None },
            if i + 1 < registry.len() { Some(registry[i + 1]) } else { None },
        ),
    }
}

pub fn find_component_entry(slug: &str) -> Option<&'static RegistryEntry> {
    find_in(COMPONENT_REGISTRY, slug)
}

pub fn component_prev_next(slug: &str) -> (Option<&'static RegistryEntry>, Option<&'static RegistryEntry>) {
    prev_next_in(COMPONENT_REGISTRY, slug)
}

pub fn find_hook_entry(slug: &str) -> Option<&'static RegistryEntry> {
    find_in(HOOKS_REGISTRY, slug)
}

pub fn hook_prev_next(slug: &str) -> (Option<&'static RegistryEntry>, Option<&'static RegistryEntry>) {
    prev_next_in(HOOKS_REGISTRY, slug)
}

pub fn find_get_started_entry(slug: &str) -> Option<&'static RegistryEntry> {
    find_in(GET_STARTED_REGISTRY, slug)
}

pub fn get_started_prev_next(slug: &str) -> (Option<&'static RegistryEntry>, Option<&'static RegistryEntry>) {
    prev_next_in(GET_STARTED_REGISTRY, slug)
}
