// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_accordion::DemoAccordion;
use registry::demos::demo_accordion_bordered::DemoAccordionBordered;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static ACCORDION: RegistryEntry = RegistryEntry {
    slug: "accordion",
    raw: include_str!("../../public/docs/accordion.md"),
    tags: &[],
    components: accordion_components,
};

fn accordion_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAccordion", |_| rsx! { DemoAccordion {} });
    c.add("DemoAccordionBordered", |_| rsx! { DemoAccordionBordered {} });
    c.add("InstallAccordion", |_| rsx! {
        InstallCommand {
            name: "accordion",
            demo_name: "demo_accordion",
            raw_code: include_str!("../../app_crates/registry/src/ui/accordion.rs"),
        }
    });
    c
}
