// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_alert_dialog::DemoAlertDialog;
use registry::demos::demo_alert_dialog_small_media::DemoAlertDialogSmallMedia;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static ALERT_DIALOG: RegistryEntry = RegistryEntry {
    slug: "alert-dialog",
    raw: include_str!("../../public/docs/alert_dialog.md"),
    tags: &[],
    components: alert_dialog_components,
};

fn alert_dialog_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAlertDialog", |_| rsx! { DemoAlertDialog {} });
    c.add("DemoAlertDialogSmallMedia", |_| rsx! { DemoAlertDialogSmallMedia {} });
    c
}
