// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_alert::DemoAlert;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static ALERT: RegistryEntry = RegistryEntry {
    slug: "alert",
    raw: include_str!("../../public/docs/alert.md"),
    tags: &[],
    components: alert_components,
};

fn alert_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAlert", |_| rsx! { DemoAlert {} });
    c.add("InstallAlert", |_| {
        rsx! {
            InstallCommand {
                name: "alert",
                demo_name: "demo_alert",
                raw_code: include_str!("../../app_crates/registry/src/ui/alert.rs"),
            }
        }
    });
    c
}
