// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_alert::DemoAlert;
use super::RegistryEntry;

pub static ALERT: RegistryEntry = RegistryEntry {
    slug: "alert",
    raw: include_str!("../../public/docs/alert.md"),
    tags: &[],
    components: alert_components,
};

fn alert_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAlert", |_| rsx! { DemoAlert {} });
    c
}
