// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_alert_dialog::DemoAlertDialog;
use crate::demos::demo_alert_dialog_media::DemoAlertDialogMedia;
use crate::demos::demo_alert_dialog_rtl::DemoAlertDialogRtl;
use crate::demos::demo_alert_dialog_small::DemoAlertDialogSmall;
use super::RegistryEntry;

pub static ALERT_DIALOG: RegistryEntry = RegistryEntry {
    slug: "alert-dialog",
    raw: include_str!("../../public/docs/alert_dialog.md"),
    tags: &[],
    components: alert_dialog_components,
};

fn alert_dialog_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAlertDialog", |_| rsx! { DemoAlertDialog {} });
    c.add("DemoAlertDialogMedia", |_| rsx! { DemoAlertDialogMedia {} });
    c.add("DemoAlertDialogRtl", |_| rsx! { DemoAlertDialogRtl {} });
    c.add("DemoAlertDialogSmall", |_| rsx! { DemoAlertDialogSmall {} });
    c
}
