// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_animate_group::DemoAnimateGroup;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static ANIMATE_GROUP: RegistryEntry = RegistryEntry {
    slug: "animate-group",
    raw: include_str!("../../public/docs/animate_group.md"),
    tags: &[],
    components: animate_group_components,
};

fn animate_group_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAnimateGroup", |_| rsx! { DemoAnimateGroup {} });
    c
}
