// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_animate::DemoAnimate;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static ANIMATE: RegistryEntry = RegistryEntry {
    slug: "animate",
    raw: include_str!("../../public/docs/animate.md"),
    tags: &[],
    components: animate_components,
};

fn animate_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAnimate", |_| rsx! { DemoAnimate {} });
    c.add("InstallAnimate", |_| {
        rsx! {
            InstallCommand {
                name: "animate",
                demo_name: "demo_animate",
                raw_code: include_str!("../../app_crates/registry/src/ui/animate.rs"),
            }
        }
    });
    c
}
