// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_attachment::DemoAttachment;
use registry::demos::demo_attachment_image::DemoAttachmentImage;
use registry::demos::demo_attachment_states::DemoAttachmentStates;
use registry::demos::demo_attachment_sizes::DemoAttachmentSizes;
use registry::demos::demo_attachment_group::DemoAttachmentGroup;
use registry::demos::demo_attachment_trigger::DemoAttachmentTrigger;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static ATTACHMENT: RegistryEntry = RegistryEntry {
    slug: "attachment",
    raw: include_str!("../../public/docs/attachment.md"),
    tags: &[],
    components: attachment_components,
};

fn attachment_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAttachment", |_| rsx! { DemoAttachment {} });
    c.add("DemoAttachmentImage", |_| rsx! { DemoAttachmentImage {} });
    c.add("DemoAttachmentStates", |_| rsx! { DemoAttachmentStates {} });
    c.add("DemoAttachmentSizes", |_| rsx! { DemoAttachmentSizes {} });
    c.add("DemoAttachmentGroup", |_| rsx! { DemoAttachmentGroup {} });
    c.add("DemoAttachmentTrigger", |_| rsx! { DemoAttachmentTrigger {} });
    c
}
