// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_auto_form::DemoAutoForm;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static AUTO_FORM: RegistryEntry = RegistryEntry {
    slug: "auto-form",
    raw: include_str!("../../public/docs/auto_form.md"),
    tags: &[],
    components: auto_form_components,
};

fn auto_form_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAutoForm", |_| rsx! { DemoAutoForm {} });
    c.add("InstallAutoForm", |_| {
        rsx! {
            InstallCommand {
                name: "auto-form",
                demo_name: "demo_auto_form",
                raw_code: include_str!("../../app_crates/registry/src/ui/auto_form.rs"),
            }
        }
    });
    c
}
