// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_avatar::DemoAvatar;
use crate::demos::demo_avatar_group_count_icon::DemoAvatarGroupCountIcon;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static AVATAR: RegistryEntry = RegistryEntry {
    slug: "avatar",
    raw: include_str!("../../public/docs/avatar.md"),
    tags: &[],
    components: avatar_components,
};

fn avatar_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoAvatar", |_| rsx! { DemoAvatar {} });
    c.add(
        "DemoAvatarGroupCountIcon",
        |_| rsx! { DemoAvatarGroupCountIcon {} },
    );
    c
}
