// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_badge::DemoBadge;
use registry::demos::demo_badge_colors::DemoBadgeColors;
use registry::demos::demo_badge_custom::DemoBadgeCustom;
use registry::demos::demo_badge_variants::DemoBadgeVariants;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static BADGE: RegistryEntry = RegistryEntry {
    slug: "badge",
    raw: include_str!("../../public/docs/badge.md"),
    tags: &[],
    components: badge_components,
};

fn badge_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoBadge", |_| rsx! { DemoBadge {} });
    c.add("DemoBadgeVariants", |_| rsx! { DemoBadgeVariants {} });
    c.add("DemoBadgeColors", |_| rsx! { DemoBadgeColors {} });
    c.add("DemoBadgeCustom", |_| rsx! { DemoBadgeCustom {} });
    c.add("InstallBadge", |_| {
        rsx! {
            InstallCommand {
                name: "badge",
                demo_name: "demo_badge",
                raw_code: include_str!("../../app_crates/registry/src/ui/badge.rs"),
            }
        }
    });
    c
}
