// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_bottom_nav::DemoBottomNav;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static BOTTOM_NAV: RegistryEntry = RegistryEntry {
    slug: "bottom-nav",
    raw: include_str!("../../public/docs/bottom_nav.md"),
    tags: &[],
    components: bottom_nav_components,
};

fn bottom_nav_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoBottomNav", |_| rsx! { DemoBottomNav {} });
    c.add("InstallBottomNav", |_| {
        rsx! {
            InstallCommand {
                name: "bottom-nav",
                demo_name: "demo_bottom_nav",
                raw_code: include_str!("../../app_crates/registry/src/ui/bottom_nav.rs"),
            }
        }
    });
    c
}
