// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_breadcrumb::DemoBreadcrumb;
use super::RegistryEntry;

pub static BREADCRUMB: RegistryEntry = RegistryEntry {
    slug: "breadcrumb",
    raw: include_str!("../../public/docs/breadcrumb.md"),
    tags: &[],
    components: breadcrumb_components,
};

fn breadcrumb_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoBreadcrumb", |_| rsx! { DemoBreadcrumb {} });
    c
}
