// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_breadcrumb::DemoBreadcrumb;
use registry::demos::demo_breadcrumb_rtl::DemoBreadcrumbRtl;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static BREADCRUMB: RegistryEntry = RegistryEntry {
    slug: "breadcrumb",
    raw: include_str!("../../public/docs/breadcrumb.md"),
    tags: &[],
    components: breadcrumb_components,
};

fn breadcrumb_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoBreadcrumb", |_| rsx! { DemoBreadcrumb {} });
    c.add("DemoBreadcrumbRtl", |_| rsx! { DemoBreadcrumbRtl {} });
    c.add("InstallBreadcrumb", |_| rsx! {
        InstallCommand {
            name: "breadcrumb",
            demo_name: "demo_breadcrumb",
            raw_code: include_str!("../../app_crates/registry/src/ui/breadcrumb.rs"),
        }
    });
    c
}
