// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_bubble::DemoBubble;
use registry::demos::demo_bubble_variants::DemoBubbleVariants;
use registry::demos::demo_bubble_alignment::DemoBubbleAlignment;
use registry::demos::demo_bubble_group::DemoBubbleGroup;
use registry::demos::demo_bubble_link_button::DemoBubbleLinkButton;
use registry::demos::demo_bubble_reactions::DemoBubbleReactions;
use registry::demos::demo_bubble_collapsible::DemoBubbleCollapsible;
use registry::demos::demo_bubble_tooltip::DemoBubbleTooltip;
use registry::demos::demo_bubble_popover::DemoBubblePopover;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static BUBBLE: RegistryEntry = RegistryEntry {
    slug: "bubble",
    raw: include_str!("../../public/docs/bubble.md"),
    tags: &[],
    components: bubble_components,
};

fn bubble_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoBubble", |_| rsx! { DemoBubble {} });
    c.add("DemoBubbleVariants", |_| rsx! { DemoBubbleVariants {} });
    c.add("DemoBubbleAlignment", |_| rsx! { DemoBubbleAlignment {} });
    c.add("DemoBubbleGroup", |_| rsx! { DemoBubbleGroup {} });
    c.add("DemoBubbleLinkButton", |_| rsx! { DemoBubbleLinkButton {} });
    c.add("DemoBubbleReactions", |_| rsx! { DemoBubbleReactions {} });
    c.add("DemoBubbleCollapsible", |_| rsx! { DemoBubbleCollapsible {} });
    c.add("DemoBubbleTooltip", |_| rsx! { DemoBubbleTooltip {} });
    c.add("DemoBubblePopover", |_| rsx! { DemoBubblePopover {} });
    c
}
