// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_button_group_icon::DemoButtonGroupIcon;
use crate::demos::demo_button_group_input::DemoButtonGroupInput;
use crate::demos::demo_button_group_rtl::DemoButtonGroupRtl;
use crate::demos::demo_button_group_separator::DemoButtonGroupSeparator;
use crate::demos::demo_button_group_sizes::DemoButtonGroupSizes;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static BUTTON_GROUP: RegistryEntry = RegistryEntry {
    slug: "button-group",
    raw: include_str!("../../public/docs/button_group.md"),
    tags: &[],
    components: button_group_components,
};

fn button_group_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoButtonGroupIcon", |_| rsx! { DemoButtonGroupIcon {} });
    c.add("DemoButtonGroupInput", |_| rsx! { DemoButtonGroupInput {} });
    c.add("DemoButtonGroupRtl", |_| rsx! { DemoButtonGroupRtl {} });
    c.add(
        "DemoButtonGroupSeparator",
        |_| rsx! { DemoButtonGroupSeparator {} },
    );
    c.add("DemoButtonGroupSizes", |_| rsx! { DemoButtonGroupSizes {} });
    c
}
