// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_button_group_icon::DemoButtonGroupIcon;
use registry::demos::demo_button_group_input::DemoButtonGroupInput;
use registry::demos::demo_button_group_rtl::DemoButtonGroupRtl;
use registry::demos::demo_button_group_separator::DemoButtonGroupSeparator;
use registry::demos::demo_button_group_sizes::DemoButtonGroupSizes;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static BUTTON_GROUP: RegistryEntry = RegistryEntry {
    slug: "button-group",
    raw: include_str!("../../public/docs/button_group.md"),
    tags: &[],
    components: button_group_components,
};

fn button_group_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoButtonGroupSeparator", |_| rsx! { DemoButtonGroupSeparator {} });
    c.add("DemoButtonGroupIcon", |_| rsx! { DemoButtonGroupIcon {} });
    c.add("DemoButtonGroupSizes", |_| rsx! { DemoButtonGroupSizes {} });
    c.add("DemoButtonGroupInput", |_| rsx! { DemoButtonGroupInput {} });
    c.add("DemoButtonGroupRtl", |_| rsx! { DemoButtonGroupRtl {} });
    c
}
