// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_button_action::DemoButtonAction;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static BUTTON_ACTION: RegistryEntry = RegistryEntry {
    slug: "button-action",
    raw: include_str!("../../public/docs/button_action.md"),
    tags: &[],
    components: button_action_components,
};

fn button_action_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoButtonAction", |_| rsx! { DemoButtonAction {} });
    c
}
