// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_button::DemoButton;
use crate::demos::demo_button_disabled::DemoButtonDisabled;
use crate::demos::demo_button_group::DemoButtonGroup;
use crate::demos::demo_button_group_icon::DemoButtonGroupIcon;
use crate::demos::demo_button_group_input::DemoButtonGroupInput;
use crate::demos::demo_button_group_separator::DemoButtonGroupSeparator;
use crate::demos::demo_button_group_sizes::DemoButtonGroupSizes;
use crate::demos::demo_button_href::DemoButtonHref;
use crate::demos::demo_button_override::DemoButtonOverride;
use crate::demos::demo_button_reactive::DemoButtonReactive;
use crate::demos::demo_button_rtl::DemoButtonRtl;
use crate::demos::demo_button_sizes::DemoButtonSizes;
use crate::demos::demo_button_stateful::DemoButtonStateful;
use crate::demos::demo_button_variants::DemoButtonVariants;
use super::RegistryEntry;

pub static BUTTON: RegistryEntry = RegistryEntry {
    slug: "button",
    raw: include_str!("../../public/docs/button.md"),
    tags: &["button"],
    components: button_components,
};

fn button_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoButton", |_| rsx! { DemoButton {} });
    c.add("DemoButtonDisabled", |_| rsx! { DemoButtonDisabled {} });
    c.add("DemoButtonGroup", |_| rsx! { DemoButtonGroup {} });
    c.add("DemoButtonGroupIcon", |_| rsx! { DemoButtonGroupIcon {} });
    c.add("DemoButtonGroupInput", |_| rsx! { DemoButtonGroupInput {} });
    c.add("DemoButtonGroupSeparator", |_| rsx! { DemoButtonGroupSeparator {} });
    c.add("DemoButtonGroupSizes", |_| rsx! { DemoButtonGroupSizes {} });
    c.add("DemoButtonHref", |_| rsx! { DemoButtonHref {} });
    c.add("DemoButtonOverride", |_| rsx! { DemoButtonOverride {} });
    c.add("DemoButtonReactive", |_| rsx! { DemoButtonReactive {} });
    c.add("DemoButtonRtl", |_| rsx! { DemoButtonRtl {} });
    c.add("DemoButtonSizes", |_| rsx! { DemoButtonSizes {} });
    c.add("DemoButtonStateful", |_| rsx! { DemoButtonStateful {} });
    c.add("DemoButtonVariants", |_| rsx! { DemoButtonVariants {} });
    c
}
