// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_card::DemoCard;
use registry::demos::demo_card_action::DemoCardAction;
use registry::demos::demo_card_group::DemoCardGroup;
use registry::demos::demo_card_reverse::DemoCardReverse;
use registry::demos::demo_card_sm::DemoCardSm;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static CARD: RegistryEntry = RegistryEntry {
    slug: "card",
    raw: include_str!("../../public/docs/card.md"),
    tags: &[],
    components: card_components,
};

fn card_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCard", |_| rsx! { DemoCard {} });
    c.add("DemoCardAction", |_| rsx! { DemoCardAction {} });
    c.add("DemoCardGroup", |_| rsx! { DemoCardGroup {} });
    c.add("DemoCardReverse", |_| rsx! { DemoCardReverse {} });
    c.add("DemoCardSm", |_| rsx! { DemoCardSm {} });
    c
}
