// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_card_carousel::DemoCardCarousel;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static CARD_CAROUSEL: RegistryEntry = RegistryEntry {
    slug: "card-carousel",
    raw: include_str!("../../public/docs/card_carousel.md"),
    tags: &[],
    components: card_carousel_components,
};

fn card_carousel_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCardCarousel", |_| rsx! { DemoCardCarousel {} });
    c.add("InstallCardCarousel", |_| {
        rsx! {
            InstallCommand {
                name: "card-carousel",
                demo_name: "demo_card_carousel",
                raw_code: include_str!("../../app_crates/registry/src/ui/card_carousel.rs"),
            }
        }
    });
    c
}
