// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_card::DemoCard;
use crate::demos::demo_card_action::DemoCardAction;
use crate::demos::demo_card_group::DemoCardGroup;
use crate::demos::demo_card_reverse::DemoCardReverse;
use crate::demos::demo_card_sm::DemoCardSm;
use super::RegistryEntry;

pub static CARD: RegistryEntry = RegistryEntry {
    slug: "card",
    raw: include_str!("../../public/docs/card.md"),
    tags: &["card"],
    components: card_components,
};

fn card_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCard", |_| rsx! { DemoCard {} });
    c.add("DemoCardAction", |_| rsx! { DemoCardAction {} });
    c.add("DemoCardGroup", |_| rsx! { DemoCardGroup {} });
    c.add("DemoCardReverse", |_| rsx! { DemoCardReverse {} });
    c.add("DemoCardSm", |_| rsx! { DemoCardSm {} });
    c
}
