// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_card_carousel::DemoCardCarousel;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static CARD_CAROUSEL: RegistryEntry = RegistryEntry {
    slug: "card-carousel",
    raw: include_str!("../../public/docs/card_carousel.md"),
    tags: &[],
    components: card_carousel_components,
};

fn card_carousel_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCardCarousel", |_| rsx! { DemoCardCarousel {} });
    c
}
