// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_carousel::DemoCarousel;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static CAROUSEL: RegistryEntry = RegistryEntry {
    slug: "carousel",
    raw: include_str!("../../public/docs/carousel.md"),
    tags: &[],
    components: carousel_components,
};

fn carousel_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCarousel", |_| rsx! { DemoCarousel {} });
    c
}
