// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static CHANGELOG: RegistryEntry = RegistryEntry {
    slug: "changelog",
    raw: include_str!("../../public/docs/changelog.md"),
    tags: &[],
    components: changelog_components,
};

fn changelog_components() -> MdComponents {
    MdComponents::new()
}
