// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_chat::DemoChat;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static CHAT: RegistryEntry = RegistryEntry {
    slug: "chat",
    raw: include_str!("../../public/docs/chat.md"),
    tags: &[],
    components: chat_components,
};

fn chat_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoChat", |_| rsx! { DemoChat {} });
    c
}
