// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_checkbox::DemoCheckbox;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static CHECKBOX: RegistryEntry = RegistryEntry {
    slug: "checkbox",
    raw: include_str!("../../public/docs/checkbox.md"),
    tags: &[],
    components: checkbox_components,
};

fn checkbox_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCheckbox", |_| rsx! { DemoCheckbox {} });
    c
}
