// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_chips::DemoChips;
use super::RegistryEntry;

pub static CHIPS: RegistryEntry = RegistryEntry {
    slug: "chips",
    raw: include_str!("../../public/docs/chips.md"),
    tags: &[],
    components: chips_components,
};

fn chips_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoChips", |_| rsx! { DemoChips {} });
    c
}
