// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_chips::DemoChips;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static CHIPS: RegistryEntry = RegistryEntry {
    slug: "chips",
    raw: include_str!("../../public/docs/chips.md"),
    tags: &[],
    components: chips_components,
};

fn chips_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoChips", |_| rsx! { DemoChips {} });
    c.add("InstallChips", |_| {
        rsx! {
            InstallCommand {
                name: "chips",
                demo_name: "demo_chips",
                raw_code: include_str!("../../app_crates/registry/src/ui/chips.rs"),
            }
        }
    });
    c
}
