// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_collapsible::DemoCollapsible;
use crate::demos::demo_collapsible_basic::DemoCollapsibleBasic;
use crate::demos::demo_collapsible_file_tree::DemoCollapsibleFileTree;
use crate::demos::demo_collapsible_rtl::DemoCollapsibleRtl;
use super::RegistryEntry;

pub static COLLAPSIBLE: RegistryEntry = RegistryEntry {
    slug: "collapsible",
    raw: include_str!("../../public/docs/collapsible.md"),
    tags: &[],
    components: collapsible_components,
};

fn collapsible_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCollapsible", |_| rsx! { DemoCollapsible {} });
    c.add("DemoCollapsibleBasic", |_| rsx! { DemoCollapsibleBasic {} });
    c.add("DemoCollapsibleFileTree", |_| rsx! { DemoCollapsibleFileTree {} });
    c.add("DemoCollapsibleRtl", |_| rsx! { DemoCollapsibleRtl {} });
    c
}
