// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_collapsible::DemoCollapsible;
use registry::demos::demo_collapsible_settings::DemoCollapsibleSettings;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static COLLAPSIBLE: RegistryEntry = RegistryEntry {
    slug: "collapsible",
    raw: include_str!("../../public/docs/collapsible.md"),
    tags: &[],
    components: collapsible_components,
};

fn collapsible_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCollapsible", |_| rsx! { DemoCollapsible {} });
    c.add("DemoCollapsibleSettings", |_| rsx! { DemoCollapsibleSettings {} });
    c
}
