// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_combobox::DemoCombobox;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static COMBOBOX: RegistryEntry = RegistryEntry {
    slug: "combobox",
    raw: include_str!("../../public/docs/combobox.md"),
    tags: &[],
    components: combobox_components,
};

fn combobox_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCombobox", |_| rsx! { DemoCombobox {} });
    c
}
