// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_command::DemoCommand;
use registry::demos::demo_command_dialog::DemoCommandDialog;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static COMMAND: RegistryEntry = RegistryEntry {
    slug: "command",
    raw: include_str!("../../public/docs/command.md"),
    tags: &[],
    components: command_components,
};

fn command_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoCommand", |_| rsx! { DemoCommand {} });
    c.add("DemoCommandDialog", |_| rsx! { DemoCommandDialog {} });
    c
}
