// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_context_menu::DemoContextMenu;
use registry::demos::demo_context_menu_action::DemoContextMenuAction;
use registry::demos::demo_context_menu_rtl::DemoContextMenuRtl;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static CONTEXT_MENU: RegistryEntry = RegistryEntry {
    slug: "context-menu",
    raw: include_str!("../../public/docs/context_menu.md"),
    tags: &[],
    components: context_menu_components,
};

fn context_menu_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoContextMenu", |_| rsx! { DemoContextMenu {} });
    c.add("DemoContextMenuAction", |_| rsx! { DemoContextMenuAction {} });
    c.add("DemoContextMenuRtl", |_| rsx! { DemoContextMenuRtl {} });
    c.add("InstallContextMenu", |_| rsx! {
        InstallCommand {
            name: "context-menu",
            demo_name: "demo_context_menu",
            raw_code: include_str!("../../app_crates/registry/src/ui/context_menu.rs"),
        }
    });
    c
}
