// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_data_table::DemoDataTable;
use registry::demos::demo_data_table_filters::DemoDataTableFilters;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static DATA_TABLE: RegistryEntry = RegistryEntry {
    slug: "data-table",
    raw: include_str!("../../public/docs/data_table.md"),
    tags: &[],
    components: data_table_components,
};

fn data_table_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDataTable", |_| rsx! { DemoDataTable {} });
    c.add("DemoDataTableFilters", |_| rsx! { DemoDataTableFilters {} });
    c.add("InstallDataTable", |_| rsx! {
        InstallCommand {
            name: "data-table",
            demo_name: "demo_data_table",
            raw_code: include_str!("../../app_crates/registry/src/ui/data_table.rs"),
        }
    });
    c
}
