// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_data_grid::DemoDataGrid;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static DATA_GRID: RegistryEntry = RegistryEntry {
    slug: "data-grid",
    raw: include_str!("../../public/docs/data_grid.md"),
    tags: &[],
    components: data_grid_components,
};

fn data_grid_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDataGrid", |_| rsx! { DemoDataGrid {} });
    c.add("InstallDataGrid", |_| {
        rsx! {
            InstallCommand {
                name: "data-grid",
                demo_name: "demo_data_grid",
                raw_code: include_str!("../../app_crates/registry/src/ui/data_grid.rs"),
            }
        }
    });
    c
}
