// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_date_picker::DemoDatePicker;
use registry::demos::demo_date_picker_booked::DemoDatePickerBooked;
use registry::demos::demo_date_picker_dropdown::DemoDatePickerDropdown;
use registry::demos::demo_date_picker_dual::DemoDatePickerDual;
use registry::demos::demo_date_picker_dual_full::DemoDatePickerDualFull;
use registry::demos::demo_date_picker_presets::DemoDatePickerPresets;
use registry::demos::demo_date_picker_time::DemoDatePickerTime;
use registry::demos::demo_date_picker_week_numbers::DemoDatePickerWeekNumbers;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static DATE_PICKER: RegistryEntry = RegistryEntry {
    slug: "date-picker",
    raw: include_str!("../../public/docs/date_picker.md"),
    tags: &[],
    components: date_picker_components,
};

fn date_picker_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDatePicker", |_| rsx! { DemoDatePicker {} });
    c.add("DemoDatePickerDropdown", |_| rsx! { DemoDatePickerDropdown {} });
    c.add("DemoDatePickerDual", |_| rsx! { DemoDatePickerDual {} });
    c.add("DemoDatePickerDualFull", |_| rsx! { DemoDatePickerDualFull {} });
    c.add("DemoDatePickerPresets", |_| rsx! { DemoDatePickerPresets {} });
    c.add("DemoDatePickerTime", |_| rsx! { DemoDatePickerTime {} });
    c.add("DemoDatePickerBooked", |_| rsx! { DemoDatePickerBooked {} });
    c.add("DemoDatePickerWeekNumbers", |_| rsx! { DemoDatePickerWeekNumbers {} });
    c
}
