// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_dialog::DemoDialog;
use registry::demos::demo_dialog_scrollable::DemoDialogScrollable;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static DIALOG: RegistryEntry = RegistryEntry {
    slug: "dialog",
    raw: include_str!("../../public/docs/dialog.md"),
    tags: &[],
    components: dialog_components,
};

fn dialog_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDialog", |_| rsx! { DemoDialog {} });
    c.add("DemoDialogScrollable", |_| rsx! { DemoDialogScrollable {} });
    c.add("InstallDialog", |_| rsx! {
        InstallCommand {
            name: "dialog",
            demo_name: "demo_dialog",
            raw_code: include_str!("../../app_crates/registry/src/ui/dialog.rs"),
        }
    });
    c
}
