// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_dialog::DemoDialog;
use crate::demos::demo_dialog_scrollable::DemoDialogScrollable;
use super::RegistryEntry;

pub static DIALOG: RegistryEntry = RegistryEntry {
    slug: "dialog",
    raw: include_str!("../../public/docs/dialog.md"),
    tags: &["dialog"],
    components: dialog_components,
};

fn dialog_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDialog", |_| rsx! { DemoDialog {} });
    c.add("DemoDialogScrollable", |_| rsx! { DemoDialogScrollable {} });
    c
}
