// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_direction_provider::DemoDirectionProvider;
use registry::demos::demo_direction_provider_default::DemoDirectionProviderDefault;
use registry::demos::demo_direction_provider_rtl::DemoDirectionProviderRtl;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static DIRECTION_PROVIDER: RegistryEntry = RegistryEntry {
    slug: "direction-provider",
    raw: include_str!("../../public/docs/direction_provider.md"),
    tags: &[],
    components: direction_provider_components,
};

fn direction_provider_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDirectionProviderDefault", |_| rsx! { DemoDirectionProviderDefault {} });
    c.add("DemoDirectionProvider", |_| rsx! { DemoDirectionProvider {} });
    c.add("DemoDirectionProviderRtl", |_| rsx! { DemoDirectionProviderRtl {} });
    c
}
