// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_drawer::DemoDrawer;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static DRAWER: RegistryEntry = RegistryEntry {
    slug: "drawer",
    raw: include_str!("../../public/docs/drawer.md"),
    tags: &[],
    components: drawer_components,
};

fn drawer_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDrawer", |_| rsx! { DemoDrawer {} });
    c.add("InstallDrawer", |_| {
        rsx! {
            InstallCommand {
                name: "drawer",
                demo_name: "demo_drawer",
                raw_code: include_str!("../../app_crates/registry/src/ui/drawer.rs"),
            }
        }
    });
    c
}
