// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_dropzone_toggle::DemoDropzoneToggle;
use registry::demos::demo_dropzone::DemoDropzone;
use registry::demos::demo_dropzone_grid::DemoDropzoneGrid;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static DROPZONE: RegistryEntry = RegistryEntry {
    slug: "dropzone",
    raw: include_str!("../../public/docs/dropzone.md"),
    tags: &[],
    components: dropzone_components,
};

fn dropzone_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDropzoneToggle", |_| rsx! { DemoDropzoneToggle {} });
    c.add("DemoDropzone", |_| rsx! { DemoDropzone {} });
    c.add("DemoDropzoneGrid", |_| rsx! { DemoDropzoneGrid {} });
    c.add("InstallDropzone", |_| rsx! {
        InstallCommand {
            name: "dropzone",
            demo_name: "demo_dropzone",
            raw_code: include_str!("../../app_crates/registry/src/ui/dropzone.rs"),
        }
    });
    c
}
