// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_dropdown_menu::DemoDropdownMenu;
use registry::demos::demo_dropdown_menu_destructive::DemoDropdownMenuDestructive;
use registry::demos::demo_dropdown_menu_end::DemoDropdownMenuEnd;
use registry::demos::demo_dropdown_menu_end_outer::DemoDropdownMenuEndOuter;
use registry::demos::demo_dropdown_menu_radio::DemoDropdownMenuRadio;
use registry::demos::demo_dropdown_menu_rtl::DemoDropdownMenuRtl;
use registry::demos::demo_dropdown_menu_select::DemoDropdownMenuSelect;
use registry::demos::demo_dropdown_menu_start::DemoDropdownMenuStart;
use registry::demos::demo_dropdown_menu_start_outer::DemoDropdownMenuStartOuter;
use registry::demos::demo_dropdown_menu_user::DemoDropdownMenuUser;
use registry::demos::demo_dropdown_menu_user_icon::DemoDropdownMenuUserIcon;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static DROPDOWN_MENU: RegistryEntry = RegistryEntry {
    slug: "dropdown-menu",
    raw: include_str!("../../public/docs/dropdown_menu.md"),
    tags: &[],
    components: dropdown_menu_components,
};

fn dropdown_menu_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDropdownMenu", |_| rsx! { DemoDropdownMenu {} });
    c.add("DemoDropdownMenuDestructive", |_| rsx! { DemoDropdownMenuDestructive {} });
    c.add("DemoDropdownMenuStart", |_| rsx! { DemoDropdownMenuStart {} });
    c.add("DemoDropdownMenuEnd", |_| rsx! { DemoDropdownMenuEnd {} });
    c.add("DemoDropdownMenuStartOuter", |_| rsx! { DemoDropdownMenuStartOuter {} });
    c.add("DemoDropdownMenuEndOuter", |_| rsx! { DemoDropdownMenuEndOuter {} });
    c.add("DemoDropdownMenuUser", |_| rsx! { DemoDropdownMenuUser {} });
    c.add("DemoDropdownMenuUserIcon", |_| rsx! { DemoDropdownMenuUserIcon {} });
    c.add("DemoDropdownMenuRadio", |_| rsx! { DemoDropdownMenuRadio {} });
    c.add("DemoDropdownMenuSelect", |_| rsx! { DemoDropdownMenuSelect {} });
    c.add("DemoDropdownMenuRtl", |_| rsx! { DemoDropdownMenuRtl {} });
    c.add("InstallDropdownMenu", |_| {
        rsx! {
            InstallCommand {
                name: "dropdown-menu",
                demo_name: "demo_dropdown_menu",
                raw_code: include_str!("../../app_crates/registry/src/ui/dropdown_menu.rs"),
            }
        }
    });
    c
}
