// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_dropzone::DemoDropzone;
use registry::demos::demo_dropzone_grid::DemoDropzoneGrid;
use registry::demos::demo_dropzone_toggle::DemoDropzoneToggle;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static DROPZONE: RegistryEntry = RegistryEntry {
    slug: "dropzone",
    raw: include_str!("../../public/docs/dropzone.md"),
    tags: &[],
    components: dropzone_components,
};

fn dropzone_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoDropzone", |_| rsx! { DemoDropzone {} });
    c.add("DemoDropzoneGrid", |_| rsx! { DemoDropzoneGrid {} });
    c.add("DemoDropzoneToggle", |_| rsx! { DemoDropzoneToggle {} });
    c
}
