// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_empty::DemoEmpty;
use crate::demos::demo_empty_muted::DemoEmptyMuted;
use super::RegistryEntry;

pub static EMPTY: RegistryEntry = RegistryEntry {
    slug: "empty",
    raw: include_str!("../../public/docs/empty.md"),
    tags: &[],
    components: empty_components,
};

fn empty_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoEmpty", |_| rsx! { DemoEmpty {} });
    c.add("DemoEmptyMuted", |_| rsx! { DemoEmptyMuted {} });
    c
}
