// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_expandable::DemoExpandable;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static EXPANDABLE: RegistryEntry = RegistryEntry {
    slug: "expandable",
    raw: include_str!("../../public/docs/expandable.md"),
    tags: &[],
    components: expandable_components,
};

fn expandable_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoExpandable", |_| rsx! { DemoExpandable {} });
    c.add("InstallExpandable", |_| {
        rsx! {
            InstallCommand {
                name: "expandable",
                demo_name: "demo_expandable",
                raw_code: include_str!("../../app_crates/registry/src/ui/expandable.rs"),
            }
        }
    });
    c
}
