// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_expandable::DemoExpandable;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static EXPANDABLE: RegistryEntry = RegistryEntry {
    slug: "expandable",
    raw: include_str!("../../public/docs/expandable.md"),
    tags: &[],
    components: expandable_components,
};

fn expandable_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoExpandable", |_| rsx! { DemoExpandable {} });
    c
}
