// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_faq_transition::DemoFaqTransition;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static FAQ_TRANSITION: RegistryEntry = RegistryEntry {
    slug: "faq-transition",
    raw: include_str!("../../public/docs/faq_transition.md"),
    tags: &[],
    components: faq_transition_components,
};

fn faq_transition_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoFaqTransition", |_| rsx! { DemoFaqTransition {} });
    c
}
