// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_field::DemoField;
use registry::demos::demo_field_rtl::DemoFieldRtl;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static FIELD: RegistryEntry = RegistryEntry {
    slug: "field",
    raw: include_str!("../../public/docs/field.md"),
    tags: &[],
    components: field_components,
};

fn field_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoField", |_| rsx! { DemoField {} });
    c.add("DemoFieldRtl", |_| rsx! { DemoFieldRtl {} });
    c
}
