// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static FIGMA: RegistryEntry = RegistryEntry {
    slug: "figma",
    raw: include_str!("../../public/docs/figma.md"),
    tags: &[],
    components: figma_components,
};

fn figma_components() -> MdComponents {
    MdComponents::new()
}
