// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_auto_form::DemoAutoForm;
use registry::demos::demo_form::DemoForm;
use registry::demos::demo_form_error::DemoFormError;
use registry::demos::demo_form_fieldset::DemoFormFieldset;
use registry::demos::demo_form_group::DemoFormGroup;
use registry::demos::demo_form_select::DemoFormSelect;
use registry::demos::demo_form_validation::DemoFormValidation;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static FORM: RegistryEntry = RegistryEntry {
    slug: "form",
    raw: include_str!("../../public/docs/form.md"),
    tags: &[],
    components: form_components,
};

fn form_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoForm", |_| rsx! { DemoForm {} });
    c.add("DemoFormValidation", |_| rsx! { DemoFormValidation {} });
    c.add("DemoFormGroup", |_| rsx! { DemoFormGroup {} });
    c.add("DemoFormFieldset", |_| rsx! { DemoFormFieldset {} });
    c.add("DemoFormError", |_| rsx! { DemoFormError {} });
    c.add("DemoFormSelect", |_| rsx! { DemoFormSelect {} });
    c.add("DemoAutoForm", |_| rsx! { DemoAutoForm {} });
    c
}
