// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_hover_card::DemoHoverCard;
use registry::demos::demo_hover_card_rtl::DemoHoverCardRtl;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static HOVER_CARD: RegistryEntry = RegistryEntry {
    slug: "hover-card",
    raw: include_str!("../../public/docs/hover_card.md"),
    tags: &[],
    components: hover_card_components,
};

fn hover_card_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoHoverCard", |_| rsx! { DemoHoverCard {} });
    c.add("DemoHoverCardRtl", |_| rsx! { DemoHoverCardRtl {} });
    c.add("InstallHoverCard", |_| rsx! {
        InstallCommand {
            name: "hover-card",
            demo_name: "demo_hover_card",
            raw_code: include_str!("../../app_crates/registry/src/ui/hover_card.rs"),
        }
    });
    c
}
