// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_image::DemoImage;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static IMAGE: RegistryEntry = RegistryEntry {
    slug: "image",
    raw: include_str!("../../public/docs/image.md"),
    tags: &[],
    components: image_components,
};

fn image_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoImage", |_| rsx! { DemoImage {} });
    c
}
