// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_input_otp::DemoInputOtp;
use registry::demos::demo_input_otp_separator::DemoInputOtpSeparator;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static INPUT_OTP: RegistryEntry = RegistryEntry {
    slug: "input-otp",
    raw: include_str!("../../public/docs/input_otp.md"),
    tags: &[],
    components: input_otp_components,
};

fn input_otp_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoInputOtp", |_| rsx! { DemoInputOtp {} });
    c.add("DemoInputOtpSeparator", |_| rsx! { DemoInputOtpSeparator {} });
    c
}
