// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_input_prompt::DemoInputPrompt;
use registry::demos::demo_input_prompt_with_tools::DemoInputPromptWithTools;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static INPUT_PROMPT: RegistryEntry = RegistryEntry {
    slug: "input-prompt",
    raw: include_str!("../../public/docs/input_prompt.md"),
    tags: &[],
    components: input_prompt_components,
};

fn input_prompt_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoInputPrompt", |_| rsx! { DemoInputPrompt {} });
    c.add("DemoInputPromptWithTools", |_| rsx! { DemoInputPromptWithTools {} });
    c.add("InstallInputPrompt", |_| {
        rsx! {
            InstallCommand {
                name: "input-prompt",
                demo_name: "demo_input_prompt",
                raw_code: include_str!("../../app_crates/registry/src/ui/input_prompt.rs"),
            }
        }
    });
    c
}
