// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_input::DemoInput;
use crate::demos::demo_input_copy::DemoInputCopy;
use crate::demos::demo_input_rtl::DemoInputRtl;
use super::RegistryEntry;

pub static INPUT: RegistryEntry = RegistryEntry {
    slug: "input",
    raw: include_str!("../../public/docs/input.md"),
    tags: &["input"],
    components: input_components,
};

fn input_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoInput", |_| rsx! { DemoInput {} });
    c.add("DemoInputCopy", |_| rsx! { DemoInputCopy {} });
    c.add("DemoInputRtl", |_| rsx! { DemoInputRtl {} });
    c
}
