// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_input_phone::DemoInputPhone;
use registry::demos::demo_input_phone_disabled::DemoInputPhoneDisabled;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static INPUT_PHONE: RegistryEntry = RegistryEntry {
    slug: "input-phone",
    raw: include_str!("../../public/docs/input_phone.md"),
    tags: &[],
    components: input_phone_components,
};

fn input_phone_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoInputPhone", |_| rsx! { DemoInputPhone {} });
    c.add("DemoInputPhoneDisabled", |_| rsx! { DemoInputPhoneDisabled {} });
    c
}
