// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static INSTALLATION: RegistryEntry = RegistryEntry {
    slug: "installation",
    raw: include_str!("../../public/docs/installation.md"),
    tags: &[],
    components: installation_components,
};

fn installation_components() -> MdComponents {
    MdComponents::new()
}
