// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static INTRODUCTION: RegistryEntry = RegistryEntry {
    slug: "introduction",
    raw: include_str!("../../public/docs/introduction.md"),
    tags: &[],
    components: introduction_components,
};

fn introduction_components() -> MdComponents {
    MdComponents::new()
}
