// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_item::DemoItem;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static ITEM: RegistryEntry = RegistryEntry {
    slug: "item",
    raw: include_str!("../../public/docs/item.md"),
    tags: &[],
    components: item_components,
};

fn item_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoItem", |_| rsx! { DemoItem {} });
    c
}
