// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_kbd::DemoKbd;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static KBD: RegistryEntry =
    RegistryEntry { slug: "kbd", raw: include_str!("../../public/docs/kbd.md"), tags: &[], components: kbd_components };

fn kbd_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoKbd", |_| rsx! { DemoKbd {} });
    c
}
