// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_kbd::DemoKbd;
use crate::demos::demo_kbd_button::DemoKbdButton;
use crate::demos::demo_kbd_combination::DemoKbdCombination;
use crate::demos::demo_kbd_rtl::DemoKbdRtl;
use super::RegistryEntry;

pub static KBD: RegistryEntry = RegistryEntry {
    slug: "kbd",
    raw: include_str!("../../public/docs/kbd.md"),
    tags: &["display", "typography"],
    components: kbd_components,
};

fn kbd_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoKbd", |_| rsx! { DemoKbd {} });
    c.add("DemoKbdButton", |_| rsx! { DemoKbdButton {} });
    c.add("DemoKbdCombination", |_| rsx! { DemoKbdCombination {} });
    c.add("DemoKbdRtl", |_| rsx! { DemoKbdRtl {} });
    c
}
