// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_kbd::DemoKbd;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static KBD: RegistryEntry = RegistryEntry {
    slug: "kbd",
    raw: include_str!("../../public/docs/kbd.md"),
    tags: &[],
    components: kbd_components,
};

fn kbd_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoKbd", |_| rsx! { DemoKbd {} });
    c.add("InstallKbd", |_| rsx! {
        InstallCommand {
            name: "kbd",
            demo_name: "demo_kbd",
            raw_code: include_str!("../../app_crates/registry/src/ui/kbd.rs"),
        }
    });
    c
}
