// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_label::DemoLabel;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static LABEL: RegistryEntry = RegistryEntry {
    slug: "label",
    raw: include_str!("../../public/docs/label.md"),
    tags: &[],
    components: label_components,
};

fn label_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoLabel", |_| rsx! { DemoLabel {} });
    c
}
