// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_label::DemoLabel;
use super::RegistryEntry;

pub static LABEL: RegistryEntry = RegistryEntry {
    slug: "label",
    raw: include_str!("../../public/docs/label.md"),
    tags: &[],
    components: label_components,
};

fn label_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoLabel", |_| rsx! { DemoLabel {} });
    c
}
