// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_marker::DemoMarker;
use registry::demos::demo_marker_variants::DemoMarkerVariants;
use registry::demos::demo_marker_border::DemoMarkerBorder;
use registry::demos::demo_marker_separator::DemoMarkerSeparator;
use registry::demos::demo_marker_icon::DemoMarkerIcon;
use registry::demos::demo_marker_status::DemoMarkerStatus;
use registry::demos::demo_marker_shimmer::DemoMarkerShimmer;
use registry::demos::demo_marker_link_button::DemoMarkerLinkButton;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static MARKER: RegistryEntry = RegistryEntry {
    slug: "marker",
    raw: include_str!("../../public/docs/marker.md"),
    tags: &[],
    components: marker_components,
};

fn marker_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoMarker", |_| rsx! { DemoMarker {} });
    c.add("DemoMarkerVariants", |_| rsx! { DemoMarkerVariants {} });
    c.add("DemoMarkerBorder", |_| rsx! { DemoMarkerBorder {} });
    c.add("DemoMarkerSeparator", |_| rsx! { DemoMarkerSeparator {} });
    c.add("DemoMarkerIcon", |_| rsx! { DemoMarkerIcon {} });
    c.add("DemoMarkerStatus", |_| rsx! { DemoMarkerStatus {} });
    c.add("DemoMarkerShimmer", |_| rsx! { DemoMarkerShimmer {} });
    c.add("DemoMarkerLinkButton", |_| rsx! { DemoMarkerLinkButton {} });
    c.add("InstallMarker", |_| rsx! {
        InstallCommand {
            name: "marker",
            demo_name: "demo_marker",
            raw_code: include_str!("../../app_crates/registry/src/ui/marker.rs"),
        }
    });
    c
}
