// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_marquee::DemoMarquee;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static MARQUEE: RegistryEntry = RegistryEntry {
    slug: "marquee",
    raw: include_str!("../../public/docs/marquee.md"),
    tags: &[],
    components: marquee_components,
};

fn marquee_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoMarquee", |_| rsx! { DemoMarquee {} });
    c
}
