// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_mask::DemoMask;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static MASK: RegistryEntry = RegistryEntry {
    slug: "mask",
    raw: include_str!("../../public/docs/mask.md"),
    tags: &[],
    components: mask_components,
};

fn mask_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoMask", |_| rsx! { DemoMask {} });
    c.add("InstallMask", |_| {
        rsx! {
            InstallCommand {
                name: "mask",
                demo_name: "demo_mask",
                raw_code: include_str!("../../app_crates/registry/src/ui/mask.rs"),
            }
        }
    });
    c
}
