// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_menubar::DemoMenubar;
use registry::demos::demo_menubar_rtl::DemoMenubarRtl;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static MENUBAR: RegistryEntry = RegistryEntry {
    slug: "menubar",
    raw: include_str!("../../public/docs/menubar.md"),
    tags: &[],
    components: menubar_components,
};

fn menubar_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoMenubar", |_| rsx! { DemoMenubar {} });
    c.add("DemoMenubarRtl", |_| rsx! { DemoMenubarRtl {} });
    c
}
