// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_message::DemoMessage;
use registry::demos::demo_message_avatar::DemoMessageAvatar;
use registry::demos::demo_message_group::DemoMessageGroup;
use registry::demos::demo_message_header_footer::DemoMessageHeaderFooter;
use registry::demos::demo_message_actions::DemoMessageActions;
use registry::demos::demo_message_attachment::DemoMessageAttachment;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static MESSAGE: RegistryEntry = RegistryEntry {
    slug: "message",
    raw: include_str!("../../public/docs/message.md"),
    tags: &[],
    components: message_components,
};

fn message_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoMessage", |_| rsx! { DemoMessage {} });
    c.add("DemoMessageAvatar", |_| rsx! { DemoMessageAvatar {} });
    c.add("DemoMessageGroup", |_| rsx! { DemoMessageGroup {} });
    c.add("DemoMessageHeaderFooter", |_| rsx! { DemoMessageHeaderFooter {} });
    c.add("DemoMessageActions", |_| rsx! { DemoMessageActions {} });
    c.add("DemoMessageAttachment", |_| rsx! { DemoMessageAttachment {} });
    c
}
