// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

pub mod accordion;
pub mod animate;
pub mod aspect_ratio;
pub mod alert;
pub mod bento_grid;
pub mod chat;
pub mod drawer;
pub mod popover;
pub mod sheet;
pub mod bottom_nav;
pub mod card_carousel;
pub mod carousel;
pub mod expandable;
pub mod faq_transition;
pub mod hover_card;
pub mod input_otp;
pub mod item;
pub mod marquee;
pub mod mask;
pub mod pressable;
pub mod radio_button_group;
pub mod shimmer;
pub mod alert_dialog;
pub mod avatar;
pub mod badge;
pub mod callout;
pub mod breadcrumb;
pub mod button;
pub mod button_group;
pub mod card;
pub mod checkbox;
pub mod chips;
pub mod collapsible;
pub mod dialog;
pub mod empty;
pub mod field;
pub mod image;
pub mod input;
pub mod input_group;
pub mod kbd;
pub mod label;
pub mod pagination;
pub mod progress;
pub mod radio_button;
pub mod radio_group;
pub mod scroll_area;
pub mod select_native;
pub mod separator;
pub mod skeleton;
pub mod slider;
pub mod spinner;
pub mod status;
pub mod switch;
pub mod table;
pub mod tabs;
pub mod textarea;
pub mod theme_toggle;
pub mod toggle;
pub mod toggle_group;
pub mod tooltip;
pub mod types;

use types::RegistryEntry;

use accordion::ACCORDION;
use animate::ANIMATE;
use aspect_ratio::ASPECT_RATIO;
use alert::ALERT;
use bento_grid::BENTO_GRID;
use chat::CHAT;
use drawer::DRAWER;
use popover::POPOVER;
use sheet::SHEET;
use bottom_nav::BOTTOM_NAV;
use card_carousel::CARD_CAROUSEL;
use carousel::CAROUSEL;
use expandable::EXPANDABLE;
use faq_transition::FAQ_TRANSITION;
use hover_card::HOVER_CARD;
use input_otp::INPUT_OTP;
use item::ITEM;
use marquee::MARQUEE;
use mask::MASK;
use pressable::PRESSABLE;
use radio_button_group::RADIO_BUTTON_GROUP;
use shimmer::SHIMMER;
use alert_dialog::ALERT_DIALOG;
use avatar::AVATAR;
use badge::BADGE;
use callout::CALLOUT;
use breadcrumb::BREADCRUMB;
use button::BUTTON;
use button_group::BUTTON_GROUP;
use card::CARD;
use checkbox::CHECKBOX;
use chips::CHIPS;
use collapsible::COLLAPSIBLE;
use dialog::DIALOG;
use empty::EMPTY;
use field::FIELD;
use image::IMAGE;
use input::INPUT;
use input_group::INPUT_GROUP;
use kbd::KBD;
use label::LABEL;
use pagination::PAGINATION;
use progress::PROGRESS;
use radio_button::RADIO_BUTTON;
use radio_group::RADIO_GROUP;
use scroll_area::SCROLL_AREA;
use select_native::SELECT_NATIVE;
use separator::SEPARATOR;
use skeleton::SKELETON;
use slider::SLIDER;
use spinner::SPINNER;
use status::STATUS;
use switch::SWITCH;
use table::TABLE;
use tabs::TABS;
use textarea::TEXTAREA;
use theme_toggle::THEME_TOGGLE;
use toggle::TOGGLE;
use toggle_group::TOGGLE_GROUP;
use tooltip::TOOLTIP;

pub static REGISTRY: &[&RegistryEntry] = &[
    &ACCORDION,
    &ANIMATE,
    &ASPECT_RATIO,
    &ALERT,
    &BENTO_GRID,
    &CHAT,
    &DRAWER,
    &POPOVER,
    &SHEET,
    &BOTTOM_NAV,
    &CARD_CAROUSEL,
    &CAROUSEL,
    &EXPANDABLE,
    &FAQ_TRANSITION,
    &HOVER_CARD,
    &INPUT_OTP,
    &ITEM,
    &MARQUEE,
    &MASK,
    &PRESSABLE,
    &RADIO_BUTTON_GROUP,
    &SHIMMER,
    &ALERT_DIALOG,
    &AVATAR,
    &BADGE,
    &CALLOUT,
    &BREADCRUMB,
    &BUTTON,
    &BUTTON_GROUP,
    &CARD,
    &CHECKBOX,
    &CHIPS,
    &COLLAPSIBLE,
    &DIALOG,
    &EMPTY,
    &FIELD,
    &IMAGE,
    &INPUT,
    &INPUT_GROUP,
    &KBD,
    &LABEL,
    &PAGINATION,
    &PROGRESS,
    &RADIO_BUTTON,
    &RADIO_GROUP,
    &SCROLL_AREA,
    &SELECT_NATIVE,
    &SEPARATOR,
    &SKELETON,
    &SLIDER,
    &SPINNER,
    &STATUS,
    &SWITCH,
    &TABLE,
    &TABS,
    &TEXTAREA,
    &THEME_TOGGLE,
    &TOGGLE,
    &TOGGLE_GROUP,
    &TOOLTIP,
];

pub fn find(slug: &str) -> Option<&'static RegistryEntry> {
    REGISTRY.iter().copied().find(|e| e.slug == slug)
}

pub fn prev_next(slug: &str) -> (Option<&'static str>, Option<&'static str>) {
    let pos = REGISTRY.iter().position(|e| e.slug == slug);
    match pos {
        None => (None, None),
        Some(i) => (
            if i > 0 {
                Some(REGISTRY[i - 1].slug)
            } else {
                None
            },
            if i + 1 < REGISTRY.len() {
                Some(REGISTRY[i + 1].slug)
            } else {
                None
            },
        ),
    }
}
