// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

pub mod accordion;
pub mod alert;
pub mod alert_dialog;
pub mod animate;
pub mod animate_group;
pub mod aspect_ratio;
pub mod attachment;
pub mod auto_form;
pub mod avatar;
pub mod badge;
pub mod bento_grid;
pub mod bottom_nav;
pub mod breadcrumb;
pub mod bubble;
pub mod button;
pub mod button_action;
pub mod button_group;
pub mod callout;
pub mod card;
pub mod card_carousel;
pub mod carousel;
pub mod chat;
pub mod checkbox;
pub mod chips;
pub mod collapsible;
pub mod combobox;
pub mod command;
pub mod context_menu;
pub mod data_grid;
pub mod data_table;
pub mod date_picker;
pub mod dialog;
pub mod direction_provider;
pub mod drag_and_drop;
pub mod drawer;
pub mod dropdown_menu;
pub mod dropzone;
pub mod empty;
pub mod expandable;
pub mod faq_transition;
pub mod field;
pub mod form;
pub mod hover_card;
pub mod image;
pub mod input;
pub mod input_group;
pub mod input_otp;
pub mod input_phone;
pub mod input_prompt;
pub mod item;
pub mod kbd;
pub mod label;
pub mod marquee;
pub mod mask;
pub mod menubar;
pub mod message;
pub mod multi_select;
pub mod navigation_menu;
pub mod pagination;
pub mod popover;
pub mod pressable;
pub mod progress;
pub mod radio_button;
pub mod radio_button_group;
pub mod radio_group;
pub mod scroll_area;
pub mod select;
pub mod select_native;
pub mod separator;
pub mod sheet;
pub mod shimmer;
pub mod skeleton;
pub mod slider;
pub mod sonner;
pub mod spinner;
pub mod status;
pub mod switch;
pub mod table;
pub mod tabs;
pub mod textarea;
pub mod theme_toggle;
pub mod toast;
pub mod toggle;
pub mod toggle_group;
pub mod toolbar;
pub mod tooltip;
pub mod hooks;
pub mod types;

use accordion::ACCORDION;
use alert::ALERT;
use alert_dialog::ALERT_DIALOG;
use animate::ANIMATE;
use animate_group::ANIMATE_GROUP;
use aspect_ratio::ASPECT_RATIO;
use attachment::ATTACHMENT;
use auto_form::AUTO_FORM;
use avatar::AVATAR;
use badge::BADGE;
use bento_grid::BENTO_GRID;
use bottom_nav::BOTTOM_NAV;
use breadcrumb::BREADCRUMB;
use bubble::BUBBLE;
use button::BUTTON;
use button_action::BUTTON_ACTION;
use button_group::BUTTON_GROUP;
use callout::CALLOUT;
use card::CARD;
use card_carousel::CARD_CAROUSEL;
use carousel::CAROUSEL;
use chat::CHAT;
use checkbox::CHECKBOX;
use chips::CHIPS;
use collapsible::COLLAPSIBLE;
use combobox::COMBOBOX;
use command::COMMAND;
use context_menu::CONTEXT_MENU;
use data_grid::DATA_GRID;
use data_table::DATA_TABLE;
use date_picker::DATE_PICKER;
use dialog::DIALOG;
use direction_provider::DIRECTION_PROVIDER;
use drag_and_drop::DRAG_AND_DROP;
use drawer::DRAWER;
use dropdown_menu::DROPDOWN_MENU;
use dropzone::DROPZONE;
use empty::EMPTY;
use expandable::EXPANDABLE;
use faq_transition::FAQ_TRANSITION;
use field::FIELD;
use form::FORM;
use hover_card::HOVER_CARD;
use image::IMAGE;
use input::INPUT;
use input_group::INPUT_GROUP;
use input_otp::INPUT_OTP;
use input_phone::INPUT_PHONE;
use input_prompt::INPUT_PROMPT;
use item::ITEM;
use kbd::KBD;
use label::LABEL;
use marquee::MARQUEE;
use mask::MASK;
use menubar::MENUBAR;
use message::MESSAGE;
use multi_select::MULTI_SELECT;
use navigation_menu::NAVIGATION_MENU;
use pagination::PAGINATION;
use popover::POPOVER;
use pressable::PRESSABLE;
use progress::PROGRESS;
use radio_button::RADIO_BUTTON;
use radio_button_group::RADIO_BUTTON_GROUP;
use radio_group::RADIO_GROUP;
use scroll_area::SCROLL_AREA;
use select::SELECT;
use select_native::SELECT_NATIVE;
use separator::SEPARATOR;
use sheet::SHEET;
use shimmer::SHIMMER;
use skeleton::SKELETON;
use slider::SLIDER;
use sonner::SONNER;
use spinner::SPINNER;
use status::STATUS;
use switch::SWITCH;
use table::TABLE;
use tabs::TABS;
use textarea::TEXTAREA;
use theme_toggle::THEME_TOGGLE;
use toast::TOAST;
use toggle::TOGGLE;
use toggle_group::TOGGLE_GROUP;
use toolbar::TOOLBAR;
use tooltip::TOOLTIP;
use types::RegistryEntry;

pub static REGISTRY: &[&RegistryEntry] = &[
    &ACCORDION,
    &ALERT,
    &ALERT_DIALOG,
    &ANIMATE,
    &ANIMATE_GROUP,
    &ASPECT_RATIO,
    &ATTACHMENT,
    &AUTO_FORM,
    &AVATAR,
    &BADGE,
    &BENTO_GRID,
    &BOTTOM_NAV,
    &BREADCRUMB,
    &BUBBLE,
    &BUTTON,
    &BUTTON_ACTION,
    &BUTTON_GROUP,
    &CALLOUT,
    &CARD,
    &CARD_CAROUSEL,
    &CAROUSEL,
    &CHAT,
    &CHECKBOX,
    &CHIPS,
    &COLLAPSIBLE,
    &COMBOBOX,
    &COMMAND,
    &CONTEXT_MENU,
    &DATA_GRID,
    &DATA_TABLE,
    &DATE_PICKER,
    &DIALOG,
    &DIRECTION_PROVIDER,
    &DRAG_AND_DROP,
    &DRAWER,
    &DROPDOWN_MENU,
    &DROPZONE,
    &EMPTY,
    &EXPANDABLE,
    &FAQ_TRANSITION,
    &FIELD,
    &FORM,
    &HOVER_CARD,
    &IMAGE,
    &INPUT,
    &INPUT_GROUP,
    &INPUT_OTP,
    &INPUT_PHONE,
    &INPUT_PROMPT,
    &ITEM,
    &KBD,
    &LABEL,
    &MARQUEE,
    &MASK,
    &MENUBAR,
    &MESSAGE,
    &MULTI_SELECT,
    &NAVIGATION_MENU,
    &PAGINATION,
    &POPOVER,
    &PRESSABLE,
    &PROGRESS,
    &RADIO_BUTTON,
    &RADIO_BUTTON_GROUP,
    &RADIO_GROUP,
    &SCROLL_AREA,
    &SELECT,
    &SELECT_NATIVE,
    &SEPARATOR,
    &SHEET,
    &SHIMMER,
    &SKELETON,
    &SLIDER,
    &SONNER,
    &SPINNER,
    &STATUS,
    &SWITCH,
    &TABLE,
    &TABS,
    &TEXTAREA,
    &THEME_TOGGLE,
    &TOAST,
    &TOGGLE,
    &TOGGLE_GROUP,
    &TOOLBAR,
    &TOOLTIP,
];

pub fn find(slug: &str) -> Option<&'static RegistryEntry> {
    REGISTRY.iter().copied().find(|e| e.slug == slug)
}

pub fn prev_next(slug: &str) -> (Option<&'static RegistryEntry>, Option<&'static RegistryEntry>) {
    let pos = REGISTRY.iter().position(|e| e.slug == slug);
    match pos {
        None => (None, None),
        Some(i) => (
            if i > 0 { Some(REGISTRY[i - 1]) } else { None },
            if i + 1 < REGISTRY.len() { Some(REGISTRY[i + 1]) } else { None },
        ),
    }
}
