// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_multi_select::DemoMultiSelect;
use registry::demos::demo_multi_select_align::DemoMultiSelectAlign;
use registry::demos::demo_multi_select_scrollable::DemoMultiSelectScrollable;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static MULTI_SELECT: RegistryEntry = RegistryEntry {
    slug: "multi-select",
    raw: include_str!("../../public/docs/multi_select.md"),
    tags: &[],
    components: multi_select_components,
};

fn multi_select_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoMultiSelect", |_| rsx! { DemoMultiSelect {} });
    c.add("DemoMultiSelectAlign", |_| rsx! { DemoMultiSelectAlign {} });
    c.add("DemoMultiSelectScrollable", |_| rsx! { DemoMultiSelectScrollable {} });
    c.add("InstallMultiSelect", |_| rsx! {
        InstallCommand {
            name: "multi-select",
            demo_name: "demo_multi_select",
            raw_code: include_str!("../../app_crates/registry/src/ui/multi_select.rs"),
        }
    });
    c
}
