// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_navigation_menu::DemoNavigationMenu;
use registry::demos::demo_navigation_menu_complex::DemoNavigationMenuComplex;
use registry::demos::demo_navigation_menu_rtl::DemoNavigationMenuRtl;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static NAVIGATION_MENU: RegistryEntry = RegistryEntry {
    slug: "navigation-menu",
    raw: include_str!("../../public/docs/navigation_menu.md"),
    tags: &[],
    components: navigation_menu_components,
};

fn navigation_menu_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoNavigationMenu", |_| rsx! { DemoNavigationMenu {} });
    c.add("DemoNavigationMenuComplex", |_| rsx! { DemoNavigationMenuComplex {} });
    c.add("DemoNavigationMenuRtl", |_| rsx! { DemoNavigationMenuRtl {} });
    c.add("InstallNavigationMenu", |_| {
        rsx! {
            InstallCommand {
                name: "navigation-menu",
                demo_name: "demo_navigation_menu",
                raw_code: include_str!("../../app_crates/registry/src/ui/navigation_menu.rs"),
            }
        }
    });
    c
}
