// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_pagination::DemoPagination;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static PAGINATION: RegistryEntry = RegistryEntry {
    slug: "pagination",
    raw: include_str!("../../public/docs/pagination.md"),
    tags: &[],
    components: pagination_components,
};

fn pagination_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoPagination", |_| rsx! { DemoPagination {} });
    c
}
