// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_pagination::DemoPagination;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static PAGINATION: RegistryEntry = RegistryEntry {
    slug: "pagination",
    raw: include_str!("../../public/docs/pagination.md"),
    tags: &[],
    components: pagination_components,
};

fn pagination_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoPagination", |_| rsx! { DemoPagination {} });
    c.add("InstallPagination", |_| {
        rsx! {
            InstallCommand {
                name: "pagination",
                demo_name: "demo_pagination",
                raw_code: include_str!("../../app_crates/registry/src/ui/pagination.rs"),
            }
        }
    });
    c
}
