// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_pressable::DemoPressable;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static PRESSABLE: RegistryEntry = RegistryEntry {
    slug: "pressable",
    raw: include_str!("../../public/docs/pressable.md"),
    tags: &[],
    components: pressable_components,
};

fn pressable_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoPressable", |_| rsx! { DemoPressable {} });
    c
}
