// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_progress::DemoProgress;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static PROGRESS: RegistryEntry = RegistryEntry {
    slug: "progress",
    raw: include_str!("../../public/docs/progress.md"),
    tags: &[],
    components: progress_components,
};

fn progress_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoProgress", |_| rsx! { DemoProgress {} });
    c.add("InstallProgress", |_| rsx! {
        InstallCommand {
            name: "progress",
            demo_name: "demo_progress",
            raw_code: include_str!("../../app_crates/registry/src/ui/progress.rs"),
        }
    });
    c
}
