// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_progress::DemoProgress;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static PROGRESS: RegistryEntry = RegistryEntry {
    slug: "progress",
    raw: include_str!("../../public/docs/progress.md"),
    tags: &[],
    components: progress_components,
};

fn progress_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoProgress", |_| rsx! { DemoProgress {} });
    c
}
