// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_radio_group::DemoRadioGroup;
use registry::demos::demo_radio_button_custom::DemoRadioButtonCustom;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static RADIO_GROUP: RegistryEntry = RegistryEntry {
    slug: "radio-group",
    raw: include_str!("../../public/docs/radio-group.md"),
    tags: &[],
    components: radio_group_components,
};

fn radio_group_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoRadioGroup", |_| rsx! { DemoRadioGroup {} });
    c.add("DemoRadioButtonCustom", |_| rsx! { DemoRadioButtonCustom {} });
    c
}
