// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_radio_button_custom::DemoRadioButtonCustom;
use crate::demos::demo_radio_group::DemoRadioGroup;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static RADIO_GROUP: RegistryEntry = RegistryEntry {
    slug: "radio-group",
    raw: include_str!("../../public/docs/radio-group.md"),
    tags: &[],
    components: radio_group_components,
};

fn radio_group_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoRadioGroup", |_| rsx! { DemoRadioGroup {} });
    c.add(
        "DemoRadioButtonCustom",
        |_| rsx! { DemoRadioButtonCustom {} },
    );
    c
}
