// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_radio_button::DemoRadioButton;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static RADIO_BUTTON: RegistryEntry = RegistryEntry {
    slug: "radio-button",
    raw: include_str!("../../public/docs/radio_button.md"),
    tags: &[],
    components: radio_button_components,
};

fn radio_button_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoRadioButton", |_| rsx! { DemoRadioButton {} });
    c
}
