// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_button_rtl::DemoButtonRtl;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static RTL: RegistryEntry = RegistryEntry {
    slug: "rtl",
    raw: include_str!("../../public/docs/rtl.md"),
    tags: &[],
    components: rtl_components,
};

fn rtl_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoButtonRtl", |_| rsx! { DemoButtonRtl {} });
    c
}
