// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_select::DemoSelect;
use registry::demos::demo_select_scrollable::DemoSelectScrollable;
use registry::demos::demo_select_rtl::DemoSelectRtl;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static SELECT: RegistryEntry = RegistryEntry {
    slug: "select",
    raw: include_str!("../../public/docs/select.md"),
    tags: &[],
    components: select_components,
};

fn select_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSelect", |_| rsx! { DemoSelect {} });
    c.add("DemoSelectScrollable", |_| rsx! { DemoSelectScrollable {} });
    c.add("DemoSelectRtl", |_| rsx! { DemoSelectRtl {} });
    c
}
