// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_select_native_group::DemoSelectNativeGroup;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static SELECT_NATIVE: RegistryEntry = RegistryEntry {
    slug: "select-native",
    raw: include_str!("../../public/docs/select_native.md"),
    tags: &[],
    components: select_native_components,
};

fn select_native_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSelectNativeGroup", |_| rsx! { DemoSelectNativeGroup {} });
    c
}
