// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_select_native_group::DemoSelectNativeGroup;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static SELECT_NATIVE: RegistryEntry = RegistryEntry {
    slug: "select-native",
    raw: include_str!("../../public/docs/select_native.md"),
    tags: &[],
    components: select_native_components,
};

fn select_native_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add(
        "DemoSelectNativeGroup",
        |_| rsx! { DemoSelectNativeGroup {} },
    );
    c
}
