// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_separator::DemoSeparator;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static SEPARATOR: RegistryEntry = RegistryEntry {
    slug: "separator",
    raw: include_str!("../../public/docs/separator.md"),
    tags: &[],
    components: separator_components,
};

fn separator_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSeparator", |_| rsx! { DemoSeparator {} });
    c
}
