// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_separator::DemoSeparator;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static SEPARATOR: RegistryEntry = RegistryEntry {
    slug: "separator",
    raw: include_str!("../../public/docs/separator.md"),
    tags: &[],
    components: separator_components,
};

fn separator_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSeparator", |_| rsx! { DemoSeparator {} });
    c
}
