// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_separator::DemoSeparator;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static SEPARATOR: RegistryEntry = RegistryEntry {
    slug: "separator",
    raw: include_str!("../../public/docs/separator.md"),
    tags: &[],
    components: separator_components,
};

fn separator_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSeparator", |_| rsx! { DemoSeparator {} });
    c.add("InstallSeparator", |_| rsx! {
        InstallCommand {
            name: "separator",
            demo_name: "demo_separator",
            raw_code: include_str!("../../app_crates/registry/src/ui/separator.rs"),
        }
    });
    c
}
