// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_shimmer::DemoShimmer;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static SHIMMER: RegistryEntry = RegistryEntry {
    slug: "shimmer",
    raw: include_str!("../../public/docs/shimmer.md"),
    tags: &[],
    components: shimmer_components,
};

fn shimmer_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoShimmer", |_| rsx! { DemoShimmer {} });
    c.add("InstallShimmer", |_| rsx! {
        InstallCommand {
            name: "shimmer",
            demo_name: "demo_shimmer",
            raw_code: include_str!("../../app_crates/registry/src/ui/shimmer.rs"),
        }
    });
    c
}
