// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_skeleton::DemoSkeleton;
use registry::demos::demo_skeleton_avatar::DemoSkeletonAvatar;
use registry::demos::demo_skeleton_form::DemoSkeletonForm;
use registry::demos::demo_skeleton_image::DemoSkeletonImage;
use registry::demos::demo_skeleton_table::DemoSkeletonTable;
use registry::demos::demo_skeleton_text::DemoSkeletonText;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static SKELETON: RegistryEntry = RegistryEntry {
    slug: "skeleton",
    raw: include_str!("../../public/docs/skeleton.md"),
    tags: &[],
    components: skeleton_components,
};

fn skeleton_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSkeleton", |_| rsx! { DemoSkeleton {} });
    c.add("DemoSkeletonImage", |_| rsx! { DemoSkeletonImage {} });
    c.add("DemoSkeletonAvatar", |_| rsx! { DemoSkeletonAvatar {} });
    c.add("DemoSkeletonText", |_| rsx! { DemoSkeletonText {} });
    c.add("DemoSkeletonForm", |_| rsx! { DemoSkeletonForm {} });
    c.add("DemoSkeletonTable", |_| rsx! { DemoSkeletonTable {} });
    c.add("InstallSkeleton", |_| {
        rsx! {
            InstallCommand {
                name: "skeleton",
                demo_name: "demo_skeleton",
                raw_code: include_str!("../../app_crates/registry/src/ui/skeleton.rs"),
            }
        }
    });
    c
}
