// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_skeleton::DemoSkeleton;
use crate::demos::demo_skeleton_avatar::DemoSkeletonAvatar;
use crate::demos::demo_skeleton_form::DemoSkeletonForm;
use crate::demos::demo_skeleton_image::DemoSkeletonImage;
use crate::demos::demo_skeleton_table::DemoSkeletonTable;
use crate::demos::demo_skeleton_text::DemoSkeletonText;
use super::RegistryEntry;

pub static SKELETON: RegistryEntry = RegistryEntry {
    slug: "skeleton",
    raw: include_str!("../../public/docs/skeleton.md"),
    tags: &[],
    components: skeleton_components,
};

fn skeleton_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSkeleton", |_| rsx! { DemoSkeleton {} });
    c.add("DemoSkeletonAvatar", |_| rsx! { DemoSkeletonAvatar {} });
    c.add("DemoSkeletonForm", |_| rsx! { DemoSkeletonForm {} });
    c.add("DemoSkeletonImage", |_| rsx! { DemoSkeletonImage {} });
    c.add("DemoSkeletonTable", |_| rsx! { DemoSkeletonTable {} });
    c.add("DemoSkeletonText", |_| rsx! { DemoSkeletonText {} });
    c
}
