// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_slider::DemoSlider;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static SLIDER: RegistryEntry = RegistryEntry {
    slug: "slider",
    raw: include_str!("../../public/docs/slider.md"),
    tags: &[],
    components: slider_components,
};

fn slider_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSlider", |_| rsx! { DemoSlider {} });
    c
}
