// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_slider::DemoSlider;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static SLIDER: RegistryEntry = RegistryEntry {
    slug: "slider",
    raw: include_str!("../../public/docs/slider.md"),
    tags: &[],
    components: slider_components,
};

fn slider_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSlider", |_| rsx! { DemoSlider {} });
    c.add("InstallSlider", |_| {
        rsx! {
            InstallCommand {
                name: "slider",
                demo_name: "demo_slider",
                raw_code: include_str!("../../app_crates/registry/src/ui/slider.rs"),
            }
        }
    });
    c
}
