// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_slider::DemoSlider;
use crate::demos::demo_slider_controlled::DemoSliderControlled;
use crate::demos::demo_slider_disabled::DemoSliderDisabled;
use crate::demos::demo_slider_flat::DemoSliderFlat;
use crate::demos::demo_slider_multiple::DemoSliderMultiple;
use crate::demos::demo_slider_rtl::DemoSliderRtl;
use crate::demos::demo_slider_vertical::DemoSliderVertical;
use super::RegistryEntry;

pub static SLIDER: RegistryEntry = RegistryEntry {
    slug: "slider",
    raw: include_str!("../../public/docs/slider.md"),
    tags: &[],
    components: slider_components,
};

fn slider_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSlider", |_| rsx! { DemoSlider {} });
    c.add("DemoSliderControlled", |_| rsx! { DemoSliderControlled {} });
    c.add("DemoSliderDisabled", |_| rsx! { DemoSliderDisabled {} });
    c.add("DemoSliderFlat", |_| rsx! { DemoSliderFlat {} });
    c.add("DemoSliderMultiple", |_| rsx! { DemoSliderMultiple {} });
    c.add("DemoSliderRtl", |_| rsx! { DemoSliderRtl {} });
    c.add("DemoSliderVertical", |_| rsx! { DemoSliderVertical {} });
    c
}
