// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_sonner::DemoSonner;
use registry::demos::demo_sonner_positions::DemoSonnerPositions;
use registry::demos::demo_sonner_variants::DemoSonnerVariants;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static SONNER: RegistryEntry = RegistryEntry {
    slug: "sonner",
    raw: include_str!("../../public/docs/sonner.md"),
    tags: &[],
    components: sonner_components,
};

fn sonner_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSonner", |_| rsx! { DemoSonner {} });
    c.add("DemoSonnerVariants", |_| rsx! { DemoSonnerVariants {} });
    c.add("DemoSonnerPositions", |_| rsx! { DemoSonnerPositions {} });
    c.add("InstallSonner", |_| {
        rsx! {
            InstallCommand {
                name: "sonner",
                demo_name: "demo_sonner",
                raw_code: include_str!("../../app_crates/registry/src/ui/sonner.rs"),
            }
        }
    });
    c
}
