// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_spinner::DemoSpinner;
use crate::demos::demo_spinner_button::DemoSpinnerButton;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static SPINNER: RegistryEntry = RegistryEntry {
    slug: "spinner",
    raw: include_str!("../../public/docs/spinner.md"),
    tags: &[],
    components: spinner_components,
};

fn spinner_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSpinner", |_| rsx! { DemoSpinner {} });
    c.add("DemoSpinnerButton", |_| rsx! { DemoSpinnerButton {} });
    c
}
