// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_spinner::DemoSpinner;
use registry::demos::demo_spinner_button::DemoSpinnerButton;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static SPINNER: RegistryEntry = RegistryEntry {
    slug: "spinner",
    raw: include_str!("../../public/docs/spinner.md"),
    tags: &[],
    components: spinner_components,
};

fn spinner_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSpinner", |_| rsx! { DemoSpinner {} });
    c.add("DemoSpinnerButton", |_| rsx! { DemoSpinnerButton {} });
    c
}
