// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_status::DemoStatus;
use crate::demos::demo_status_variants::DemoStatusVariants;
use super::RegistryEntry;

pub static STATUS: RegistryEntry = RegistryEntry {
    slug: "status",
    raw: include_str!("../../public/docs/status.md"),
    tags: &[],
    components: status_components,
};

fn status_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoStatus", |_| rsx! { DemoStatus {} });
    c.add("DemoStatusVariants", |_| rsx! { DemoStatusVariants {} });
    c
}
