// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_status::DemoStatus;
use registry::demos::demo_status_variants::DemoStatusVariants;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static STATUS: RegistryEntry = RegistryEntry {
    slug: "status",
    raw: include_str!("../../public/docs/status.md"),
    tags: &[],
    components: status_components,
};

fn status_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoStatus", |_| rsx! { DemoStatus {} });
    c.add("DemoStatusVariants", |_| rsx! { DemoStatusVariants {} });
    c
}
