// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_stepper::DemoStepper;
use registry::demos::demo_stepper_controlled::DemoStepperControlled;
use registry::demos::demo_stepper_vertical::DemoStepperVertical;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static STEPPER: RegistryEntry = RegistryEntry {
    slug: "stepper",
    raw: include_str!("../../public/docs/stepper.md"),
    tags: &[],
    components: stepper_components,
};

fn stepper_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoStepper", |_| rsx! { DemoStepper {} });
    c.add("DemoStepperVertical", |_| rsx! { DemoStepperVertical {} });
    c.add("DemoStepperControlled", |_| rsx! { DemoStepperControlled {} });
    c
}
