// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_switch::DemoSwitch;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static SWITCH: RegistryEntry = RegistryEntry {
    slug: "switch",
    raw: include_str!("../../public/docs/switch.md"),
    tags: &[],
    components: switch_components,
};

fn switch_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSwitch", |_| rsx! { DemoSwitch {} });
    c.add("InstallSwitch", |_| {
        rsx! {
            InstallCommand {
                name: "switch",
                demo_name: "demo_switch",
                raw_code: include_str!("../../app_crates/registry/src/ui/switch.rs"),
            }
        }
    });
    c
}
