// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_switch::DemoSwitch;
use crate::demos::demo_switch_labeled::DemoSwitchLabeled;
use super::RegistryEntry;

pub static SWITCH: RegistryEntry = RegistryEntry {
    slug: "switch",
    raw: include_str!("../../public/docs/switch.md"),
    tags: &["interactive", "form"],
    components: switch_components,
};

fn switch_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoSwitch", |_| rsx! { DemoSwitch {} });
    c.add("DemoSwitchLabeled", |_| rsx! { DemoSwitchLabeled {} });
    c
}
