// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_table::DemoTable;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static TABLE: RegistryEntry = RegistryEntry {
    slug: "table",
    raw: include_str!("../../public/docs/table.md"),
    tags: &[],
    components: table_components,
};

fn table_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoTable", |_| rsx! { DemoTable {} });
    c
}
