// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_table::DemoTable;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static TABLE: RegistryEntry = RegistryEntry {
    slug: "table",
    raw: include_str!("../../public/docs/table.md"),
    tags: &[],
    components: table_components,
};

fn table_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoTable", |_| rsx! { DemoTable {} });
    c.add("InstallTable", |_| rsx! {
        InstallCommand {
            name: "table",
            demo_name: "demo_table",
            raw_code: include_str!("../../app_crates/registry/src/ui/table.rs"),
        }
    });
    c
}
