// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_tabs::DemoTabs;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static TABS: RegistryEntry = RegistryEntry {
    slug: "tabs",
    raw: include_str!("../../public/docs/tabs.md"),
    tags: &[],
    components: tabs_components,
};

fn tabs_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoTabs", |_| rsx! { DemoTabs {} });
    c.add("InstallTabs", |_| rsx! {
        InstallCommand {
            name: "tabs",
            demo_name: "demo_tabs",
            raw_code: include_str!("../../app_crates/registry/src/ui/tabs.rs"),
        }
    });
    c
}
