// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_tabs::DemoTabs;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static TABS: RegistryEntry = RegistryEntry {
    slug: "tabs",
    raw: include_str!("../../public/docs/tabs.md"),
    tags: &[],
    components: tabs_components,
};

fn tabs_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoTabs", |_| rsx! { DemoTabs {} });
    c
}
