// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_textarea::DemoTextarea;
use crate::demos::demo_textarea_disabled::DemoTextareaDisabled;
use super::RegistryEntry;

pub static TEXTAREA: RegistryEntry = RegistryEntry {
    slug: "textarea",
    raw: include_str!("../../public/docs/textarea.md"),
    tags: &["form", "input"],
    components: textarea_components,
};

fn textarea_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoTextarea", |_| rsx! { DemoTextarea {} });
    c.add("DemoTextareaDisabled", |_| rsx! { DemoTextareaDisabled {} });
    c
}
