// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_textarea::DemoTextarea;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static TEXTAREA: RegistryEntry = RegistryEntry {
    slug: "textarea",
    raw: include_str!("../../public/docs/textarea.md"),
    tags: &[],
    components: textarea_components,
};

fn textarea_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoTextarea", |_| rsx! { DemoTextarea {} });
    c
}
