// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_theme_toggle::DemoThemeToggle;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static THEME_TOGGLE: RegistryEntry = RegistryEntry {
    slug: "theme-toggle",
    raw: include_str!("../../public/docs/theme_toggle.md"),
    tags: &[],
    components: theme_toggle_components,
};

fn theme_toggle_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoThemeToggle", |_| rsx! { DemoThemeToggle {} });
    c.add("InstallThemeToggle", |_| rsx! {
        InstallCommand {
            name: "theme-toggle",
            demo_name: "demo_theme_toggle",
            raw_code: include_str!("../../app_crates/registry/src/ui/theme_toggle.rs"),
        }
    });
    c
}
