// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use crate::markdown::converter::MdComponents;
use crate::demos::demo_theme_toggle::DemoThemeToggle;
use super::RegistryEntry;

pub static THEME_TOGGLE: RegistryEntry = RegistryEntry {
    slug: "theme-toggle",
    raw: include_str!("../../public/docs/theme_toggle.md"),
    tags: &[],
    components: theme_toggle_components,
};

fn theme_toggle_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoThemeToggle", |_| rsx! { DemoThemeToggle {} });
    c
}
