// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_toast::DemoToast;
use registry::demos::demo_toast_variants::DemoToastVariants;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static TOAST: RegistryEntry = RegistryEntry {
    slug: "toast",
    raw: include_str!("../../public/docs/toast.md"),
    tags: &[],
    components: toast_components,
};

fn toast_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoToast", |_| rsx! { DemoToast {} });
    c.add("DemoToastVariants", |_| rsx! { DemoToastVariants {} });
    c
}
