// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_toggle::DemoToggle;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static TOGGLE: RegistryEntry = RegistryEntry {
    slug: "toggle",
    raw: include_str!("../../public/docs/toggle.md"),
    tags: &[],
    components: toggle_components,
};

fn toggle_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoToggle", |_| rsx! { DemoToggle {} });
    c
}
