// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use super::RegistryEntry;
use crate::demos::demo_toggle_group::DemoToggleGroup;
use crate::markdown::converter::MdComponents;
use dioxus::prelude::*;

pub static TOGGLE_GROUP: RegistryEntry = RegistryEntry {
    slug: "toggle-group",
    raw: include_str!("../../public/docs/toggle_group.md"),
    tags: &[],
    components: toggle_group_components,
};

fn toggle_group_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoToggleGroup", |_| rsx! { DemoToggleGroup {} });
    c
}
