// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_toggle_group::DemoToggleGroup;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static TOGGLE_GROUP: RegistryEntry = RegistryEntry {
    slug: "toggle-group",
    raw: include_str!("../../public/docs/toggle_group.md"),
    tags: &[],
    components: toggle_group_components,
};

fn toggle_group_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoToggleGroup", |_| rsx! { DemoToggleGroup {} });
    c.add("InstallToggleGroup", |_| {
        rsx! {
            InstallCommand {
                name: "toggle-group",
                demo_name: "demo_toggle_group",
                raw_code: include_str!("../../app_crates/registry/src/ui/toggle_group.rs"),
            }
        }
    });
    c
}
