// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_toolbar::DemoToolbar;

use super::RegistryEntry;
use crate::components::install_command::InstallCommand;
use crate::markdown::converter::MdComponents;

pub static TOOLBAR: RegistryEntry = RegistryEntry {
    slug: "toolbar",
    raw: include_str!("../../public/docs/toolbar.md"),
    tags: &[],
    components: toolbar_components,
};

fn toolbar_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoToolbar", |_| rsx! { DemoToolbar {} });
    c.add("InstallToolbar", |_| {
        rsx! {
            InstallCommand {
                name: "toolbar",
                demo_name: "demo_toolbar",
                raw_code: include_str!("../../app_crates/registry/src/ui/toolbar.rs"),
            }
        }
    });
    c
}
