// AUTO-GENERATED by build_registry — do not edit manually.
// Run `cargo run --manifest-path dioxus_ui_internals/build_registry/Cargo.toml` to regenerate.

use dioxus::prelude::*;
use registry::demos::demo_tooltip::DemoTooltip;

use super::RegistryEntry;
use crate::markdown::converter::MdComponents;

pub static TOOLTIP: RegistryEntry = RegistryEntry {
    slug: "tooltip",
    raw: include_str!("../../public/docs/tooltip.md"),
    tags: &[],
    components: tooltip_components,
};

fn tooltip_components() -> MdComponents {
    let mut c = MdComponents::new();
    c.add("DemoTooltip", |_| rsx! { DemoTooltip {} });
    c
}
