// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use crate::markdown::converter::MdComponents;
use crate::registry::types::RegistryEntry;

pub static USE_RANDOM: RegistryEntry = RegistryEntry {
    slug: "use-random",
    raw: include_str!("../../../public/docs/hooks/use_random.md"),
    tags: &[],
    components: use_random_components,
};

fn use_random_components() -> MdComponents {
    MdComponents::new()
}
