// AUTO-GENERATED by build_registry_dioxus — do not edit manually.
// Run `cargo run --manifest-path rust_ui_internals/build_registry_dioxus/Cargo.toml` to regenerate.

use crate::markdown::converter::MdComponents;
use crate::registry::types::RegistryEntry;

pub static USE_COPY_CLIPBOARD: RegistryEntry = RegistryEntry {
    slug: "use-copy-clipboard",
    raw: include_str!("../../../public/docs/hooks/use_copy_clipboard.md"),
    tags: &[],
    components: use_copy_clipboard_components,
};

fn use_copy_clipboard_components() -> MdComponents {
    MdComponents::new()
}
